Repository Team-Going/Going-Android, pull requests merged in 2023-12, with the labels that each got.

#6 [MOD/#5] timber logging interceptor
  app/src/main/java/com/going/going/di/RetrofitModule.kt
Labels: 동민 🍕, MOD ✅

#10 [ADD/#8] 색상, 타이포 에셋 세팅
  app/src/main/AndroidManifest.xml
  presentation/src/main/res/font/font_pretendard_bold.xml
  presentation/src/main/res/font/font_pretendard_extrabold.xml
  presentation/src/main/res/font/font_pretendard_medium.xml
  presentation/src/main/res/font/font_pretendard_regular.xml
  presentation/src/main/res/font/font_pretendard_semibold.xml
  presentation/src/main/res/font/pretendard_bold.ttf
  presentation/src/main/res/font/pretendard_extrabold.ttf
  presentation/src/main/res/font/pretendard_medium.ttf
  presentation/src/main/res/font/pretendard_regular.ttf
  presentation/src/main/res/font/pretendard_semibold.ttf
  presentation/src/main/res/layout/activity_mock.xml
  presentation/src/main/res/layout/item_mock.xml
  presentation/src/main/res/values/appearances.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/themes.xml
Labels: 상호 🍀, ADD ➕

#12 [FEAT/#7] kakao login
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/going/going/MyApp.kt
  build.gradle.kts
  buildSrc/src/main/kotlin/Constants.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  domain/src/main/kotlin/com/going/domain/entity/response/AuthTokenModel.kt
  gradle/wrapper/gradle-wrapper.properties
  presentation/build.gradle.kts
  presentation/src/main/java/com/going/presentation/auth/LoginActivity.kt
  presentation/src/main/java/com/going/presentation/auth/LoginViewModel.kt
  presentation/src/main/java/com/going/presentation/mock/MockActivity.kt
  presentation/src/main/res/drawable/img_sign_in_kakao_button.png
  presentation/src/main/res/drawable/img_sign_in_main.png
  presentation/src/main/res/layout/activity_login.xml
  presentation/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: 동민 🐥, FEAT ✨
