Repository Team-Going/Going-Android, pull requests merged in 2024-01, with the labels that each got.

#17 [ADD/#16] 타이포, 색상 에셋 수정, 로고 추가
  app/src/main/AndroidManifest.xml
  presentation/src/main/ic_doorip_launcher-playstore.png
  presentation/src/main/res/mipmap-anydpi-v26/ic_doorip_launcher.xml
  presentation/src/main/res/mipmap-anydpi-v26/ic_doorip_launcher_round.xml
  presentation/src/main/res/mipmap-hdpi/ic_doorip_launcher.png
  presentation/src/main/res/mipmap-hdpi/ic_doorip_launcher_foreground.png
  presentation/src/main/res/mipmap-hdpi/ic_doorip_launcher_round.png
  presentation/src/main/res/mipmap-mdpi/ic_doorip_launcher.png
  presentation/src/main/res/mipmap-mdpi/ic_doorip_launcher_foreground.png
  presentation/src/main/res/mipmap-mdpi/ic_doorip_launcher_round.png
  presentation/src/main/res/mipmap-xhdpi/ic_doorip_launcher.png
  presentation/src/main/res/mipmap-xhdpi/ic_doorip_launcher_foreground.png
  presentation/src/main/res/mipmap-xhdpi/ic_doorip_launcher_round.png
  presentation/src/main/res/mipmap-xxhdpi/ic_doorip_launcher.png
  presentation/src/main/res/mipmap-xxhdpi/ic_doorip_launcher_foreground.png
  presentation/src/main/res/mipmap-xxhdpi/ic_doorip_launcher_round.png
  presentation/src/main/res/mipmap-xxxhdpi/ic_doorip_launcher.png
  presentation/src/main/res/mipmap-xxxhdpi/ic_doorip_launcher_foreground.png
  presentation/src/main/res/mipmap-xxxhdpi/ic_doorip_launcher_round.png
  presentation/src/main/res/values/appearances.xml
  presentation/src/main/res/values/colors.xml
Labels: 상호 🍀, ADD ➕

#14 [UI/#13] onboarding profile setting
  app/src/main/AndroidManifest.xml
  core-ui/src/main/java/com/going/ui/extension/ContextExt.kt
  domain/src/main/kotlin/com/going/domain/entity/NameState.kt
  presentation/src/main/java/com/going/presentation/onboarding/OnboardingProfileSettingActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/OnboardingProfileSettingViewModel.kt
  presentation/src/main/res/drawable/sel_rounded_corner_button.xml
  presentation/src/main/res/drawable/sel_rounded_corner_edit_text.xml
  presentation/src/main/res/drawable/sel_rounded_corner_edit_text_error.xml
  presentation/src/main/res/layout/activity_login.xml
  presentation/src/main/res/layout/activity_onboarding_profile_setting.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: 동민 🐥, UI 💐

#19 [FIX/#18] 색상코드 변경
  presentation/src/main/java/com/going/presentation/onboarding/OnboardingProfileSettingActivity.kt
  presentation/src/main/res/drawable/sel_rounded_corner_edit_text_error.xml
  presentation/src/main/res/layout/activity_onboarding_profile_setting.xml
Labels: 동민 🐥, FIX 🔨

#23 [UI/#21] 성향테스트뷰 UI / Animation 구현
  app/src/main/AndroidManifest.xml
  domain/src/main/kotlin/com/going/domain/entity/TendencyTestMock.kt
  presentation/src/main/java/com/going/presentation/tendencytest/TendencyTestActivity.kt
  presentation/src/main/java/com/going/presentation/tendencytest/TendencyTestSplashActivity.kt
  presentation/src/main/java/com/going/presentation/tendencytest/TendencyTestViewModel.kt
  presentation/src/main/res/drawable/ll_progressbar.xml
  presentation/src/main/res/drawable/sel_radiobutton.xml
  presentation/src/main/res/drawable/sel_radiobutton_checked.xml
  presentation/src/main/res/drawable/sel_radiobutton_unchecked.xml
  presentation/src/main/res/layout/activity_onboarding_profile_setting.xml
  presentation/src/main/res/layout/activity_tendency_test.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: 동민 🐥, UI 💐

#24 [UI/#9] 취향 태그 뷰 / UI 구현
  app/src/main/AndroidManifest.xml
  domain/src/main/kotlin/com/going/domain/entity/PreferenceData.kt
  presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagActivity.kt
  presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagAdapter.kt
  presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagViewHolder.kt
  presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagViewModel.kt
  presentation/src/main/res/drawable/ic_round_gray.xml
  presentation/src/main/res/drawable/sel_radiobutton_text_color.xml
  presentation/src/main/res/drawable/sel_rounded_corner_preference_tag_button.xml
  presentation/src/main/res/drawable/shape_rect_5_white000_fill.xml
  presentation/src/main/res/drawable/shape_rect_topleft5_gray300_fill.xml
  presentation/src/main/res/layout/activity_preference_tag.xml
  presentation/src/main/res/layout/item_preference_tag.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: 유빈 ❄, UI 💐

#25 [UI/#11] OurTodo / 투두 리스트 제외 UI & 기능 구현
  app/src/main/AndroidManifest.xml
  domain/src/main/kotlin/com/going/domain/entity/response/TripParticipantsListModel.kt
  presentation/src/main/java/com/going/presentation/todo/TodoActivity.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoUncompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoViewPagerAdapter.kt
  presentation/src/main/res/drawable/ic_back.xml
  presentation/src/main/res/drawable/ic_calendar.xml
  presentation/src/main/res/drawable/ic_enter.xml
  presentation/src/main/res/drawable/ic_plus.xml
  presentation/src/main/res/drawable/ic_todo_add_background.xml
  presentation/src/main/res/drawable/ic_todo_add_friend.xml
  presentation/src/main/res/drawable/ic_todo_friend.png
  presentation/src/main/res/drawable/ic_todo_ticket_left.xml
  presentation/src/main/res/drawable/ic_todo_ticket_right.xml
  presentation/src/main/res/drawable/ic_todo_trip_fix.xml
  presentation/src/main/res/drawable/layer_list_todo_progress_bar.xml
  presentation/src/main/res/drawable/sel_todo_shape_tv_name.xml
  presentation/src/main/res/drawable/shape_line_gray100_fill_dash_8.xml
  presentation/src/main/res/drawable/shape_rect_4_gray50_fill.xml
  presentation/src/main/res/drawable/shape_rect_56_red500_fill.xml
  presentation/src/main/res/drawable/shape_rect_8_white000_fill_gray100_line.xml
  presentation/src/main/res/layout/activity_todo.xml
  presentation/src/main/res/layout/fragment_my_todo.xml
  presentation/src/main/res/layout/fragment_our_todo.xml
  presentation/src/main/res/layout/fragment_our_todo_complete.xml
  presentation/src/main/res/layout/fragment_our_todo_uncomplete.xml
  presentation/src/main/res/layout/item_our_todo.xml
  presentation/src/main/res/layout/item_todo_friends.xml
  presentation/src/main/res/menu/menu_todo.xml
  presentation/src/main/res/values/strings.xml
Labels: 상호 🍀, UI 💐

#29 [Fix/#27] style 셋팅
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/going/presentation/onboarding/OnboardingProfileSettingActivity.kt
  presentation/src/main/java/com/going/presentation/tendencytest/TendencyTestActivity.kt
  presentation/src/main/java/com/going/presentation/tendencytest/TendencyTestSplashActivity.kt
  presentation/src/main/java/com/going/presentation/tendencytest/TendencyTestViewModel.kt
  presentation/src/main/res/drawable/layer_list_progressbar.xml
  presentation/src/main/res/drawable/sel_radiobutton_checked.xml
  presentation/src/main/res/drawable/sel_radiobutton_unchecked.xml
  presentation/src/main/res/drawable/sel_rounded_corner_edit_text.xml
  presentation/src/main/res/drawable/sel_rounded_corner_edit_text_empty.xml
  presentation/src/main/res/drawable/sel_rounded_corner_edit_text_error.xml
  presentation/src/main/res/drawable/shape_rect_4_gray200_line.xml
  presentation/src/main/res/drawable/shape_rect_4_gray700_line.xml
  presentation/src/main/res/drawable/shape_rect_4_red500_line.xml
  presentation/src/main/res/drawable/shape_rect_8_gray50_fill.xml
  presentation/src/main/res/drawable/shape_rect_8_red500_line.xml
  presentation/src/main/res/layout/activity_onboarding_profile_setting.xml
  presentation/src/main/res/layout/activity_tendency_test.xml
  presentation/src/main/res/values/themes.xml
Labels: 동민 🐥, FIX 🔨

#32 [UI/#31] OurTodo / 완료, 미완료 투두리스트 구현
  app/src/main/AndroidManifest.xml
  domain/src/main/kotlin/com/going/domain/entity/response/TodoModel.kt
  presentation/src/main/java/com/going/presentation/todo/name/TodoNameAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/name/TodoNameViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFriendAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFriendViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoListAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoListViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoUncompleteFragment.kt
  presentation/src/main/res/drawable/ic_mytodo_selected.xml
  presentation/src/main/res/drawable/ic_mytodo_unselected.xml
  presentation/src/main/res/drawable/ic_ourtodo_selected.xml
  presentation/src/main/res/drawable/ic_ourtodo_unselected.xml
  presentation/src/main/res/drawable/layer_list_todo_unselected_indicator.xml
  presentation/src/main/res/drawable/sel_bnv_icon_my_todo.xml
  presentation/src/main/res/drawable/sel_bnv_icon_our_todo.xml
  presentation/src/main/res/drawable/sel_bnv_label_color.xml
  presentation/src/main/res/drawable/sel_todo_shape_tv_name.xml
  presentation/src/main/res/drawable/shape_rect_2_gray300_line.xml
  presentation/src/main/res/layout/activity_todo.xml
  presentation/src/main/res/layout/fragment_our_todo.xml
  presentation/src/main/res/layout/fragment_our_todo_complete.xml
  presentation/src/main/res/layout/fragment_our_todo_uncomplete.xml
  presentation/src/main/res/layout/item_our_todo.xml
  presentation/src/main/res/layout/item_todo_name.xml
  presentation/src/main/res/menu/menu_todo.xml
  presentation/src/main/res/values/strings.xml
Labels: 상호 🍀, UI 💐

#34 [UI/#28] 유형검사 결과 페이지
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/going/going/di/DataSourceModule.kt
  app/src/main/java/com/going/going/di/RepositoryModule.kt
  app/src/main/java/com/going/going/di/ServiceModule.kt
  data/src/main/java/com/going/data/datasource/LoginDataSource.kt
  data/src/main/java/com/going/data/datasourceImpl/LoginDataSourceImpl.kt
  data/src/main/java/com/going/data/dto/BaseResponse.kt
  data/src/main/java/com/going/data/dto/request/RequestLoginDto.kt
  data/src/main/java/com/going/data/dto/response/LoginResponseDto.kt
  data/src/main/java/com/going/data/repositoryImpl/LoginRepositoryImpl.kt
  data/src/main/java/com/going/data/service/LoginService.kt
  domain/src/main/kotlin/com/going/domain/entity/TendencyResultMock.kt
  domain/src/main/kotlin/com/going/domain/entity/response/AuthTokenModel.kt
  domain/src/main/kotlin/com/going/domain/repository/LoginRepository.kt
  presentation/src/main/java/com/going/presentation/auth/LoginActivity.kt
  presentation/src/main/java/com/going/presentation/auth/LoginViewModel.kt
  presentation/src/main/java/com/going/presentation/tendencytest/result/TendencyTestResultActivity.kt
  presentation/src/main/java/com/going/presentation/tendencytest/result/TendencyTestResultViewModel.kt
  presentation/src/main/res/drawable/ic_save_btn.xml
  presentation/src/main/res/drawable/img_blur.xml
  presentation/src/main/res/drawable/sel_rounded_corner_button.xml
  presentation/src/main/res/drawable/shape_line_gray100_fill_dash_4.xml
  presentation/src/main/res/drawable/shape_line_gray100_fill_dash_4_vertical.xml
  presentation/src/main/res/drawable/shape_rect_10_red300_line.xml
  presentation/src/main/res/drawable/shape_rect_4_gray500_fill.xml
  presentation/src/main/res/drawable/shape_rect_6_gray200_line.xml
  presentation/src/main/res/drawable/shape_rect_topleft_8_topright_8_white000_fill.xml
  presentation/src/main/res/layout/activity_onboarding_profile_setting.xml
  presentation/src/main/res/layout/activity_tendency_test.xml
  presentation/src/main/res/layout/activity_tendency_test_result.xml
  presentation/src/main/res/layout/activity_tendency_test_splash.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: 동민 🐥, UI 💐

#38 [UI/#35] splash screen 구현
  app/src/main/AndroidManifest.xml
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/going/presentation/auth/SignInActivity.kt
  presentation/src/main/java/com/going/presentation/auth/SignInViewModel.kt
  presentation/src/main/java/com/going/presentation/splash/NetworkManager.kt
  presentation/src/main/java/com/going/presentation/splash/SplashActivity.kt
  presentation/src/main/java/com/going/presentation/tendencytest/result/TendencyTestResultActivity.kt
  presentation/src/main/res/drawable/text_logo_doorip.xml
  presentation/src/main/res/layout/activity_splash.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: 동민 🐥, UI 💐

#40 [UI/#39] signin ui 수정 및 웹페이지 연결
  presentation/src/main/java/com/going/presentation/auth/SignInActivity.kt
  presentation/src/main/java/com/going/presentation/splash/SplashActivity.kt
  presentation/src/main/res/drawable/ic_warning_mini.xml
  presentation/src/main/res/drawable/img_sign_in_kakao_button.png
  presentation/src/main/res/drawable/text_logo_doorip_red500.xml
  presentation/src/main/res/drawable/text_logo_doorip_white000.xml
  presentation/src/main/res/layout/activity_login.xml
  presentation/src/main/res/layout/activity_signin.xml
  presentation/src/main/res/layout/activity_splash.xml
  presentation/src/main/res/values/strings.xml
Labels: 동민 🐥, UI 💐

#42 [UI/#30] 여행 대시 보드 뷰 / UI 구현
  app/src/main/AndroidManifest.xml
  domain/src/main/kotlin/com/going/domain/entity/response/CompletedListModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/OngoingListModel.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/DashBoardViewPagerAdapter.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/TripDashBoardActivity.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/TripDashBoardViewModel.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/triplist/CompletedAdapter.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/triplist/CompletedTripFragment.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/triplist/CompletedViewHolder.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/triplist/OngoingAdapter.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/triplist/OngoingTripFragment.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/triplist/OngoingViewHolder.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/triplist/TripDecoration.kt
  presentation/src/main/res/drawable/ic_btn_setting.xml
  presentation/src/main/res/drawable/ic_dash_board_blur.xml
  presentation/src/main/res/drawable/ic_empty_doorip.xml
  presentation/src/main/res/drawable/layer_list_trip_dash_board_view_pager.xml
  presentation/src/main/res/drawable/shape_rect_2_gray100_fill.xml
  presentation/src/main/res/drawable/shape_rect_2_red100_fill.xml
  presentation/src/main/res/drawable/shape_rect_4_white000_fill.xml
  presentation/src/main/res/layout/activity_trip_dash_board.xml
  presentation/src/main/res/layout/fragment_completed_trip.xml
  presentation/src/main/res/layout/fragment_ongoing_trip.xml
  presentation/src/main/res/layout/item_dash_board_completed.xml
  presentation/src/main/res/layout/item_dash_board_ongoing.xml
  presentation/src/main/res/values/strings.xml
Labels: 유빈 ❄, UI 💐

#43 [UI/#33] MyTodo UI 구현
  app/src/main/AndroidManifest.xml
  domain/src/main/kotlin/com/going/domain/entity/response/TodoModel.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoListAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoListViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoUncompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoViewPagerAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoListViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoUncompleteFragment.kt
  presentation/src/main/res/drawable/ic_lock_complete.xml
  presentation/src/main/res/drawable/ic_lock_uncomplete.xml
  presentation/src/main/res/drawable/ic_my_todo_checkbox_selected.xml
  presentation/src/main/res/drawable/ic_my_todo_checkbox_unselected.xml
  presentation/src/main/res/drawable/ic_profile.xml
  presentation/src/main/res/drawable/shape_rect_2_gray400_line.xml
  presentation/src/main/res/layout/fragment_my_todo.xml
  presentation/src/main/res/layout/fragment_my_todo_complete.xml
  presentation/src/main/res/layout/fragment_my_todo_uncomplete.xml
  presentation/src/main/res/layout/fragment_our_todo.xml
  presentation/src/main/res/layout/item_my_todo.xml
  presentation/src/main/res/values/strings.xml
Labels: 상호 🍀, UI 💐

#46 [UI/#37] 여행 입장 스플래시 구현
  app/src/main/AndroidManifest.xml
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/going/presentation/starttrip/StartTripSplashActivity.kt
  presentation/src/main/java/com/going/presentation/starttrip/createtrip/BottomSheetDateContentFragment.kt
  presentation/src/main/java/com/going/presentation/starttrip/createtrip/CreateTripActivity.kt
  presentation/src/main/java/com/going/presentation/starttrip/createtrip/CreateTripViewModel.kt
  presentation/src/main/res/layout/activity_create_trip.xml
  presentation/src/main/res/layout/activity_start_trip_splash.xml
  presentation/src/main/res/layout/fragment_bottom_sheet_date_content.xml
  presentation/src/main/res/values/strings.xml
Labels: 세연 🤤, UI 💐

#48 [UI/#47] 여행 생성 완료 뷰 구현
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/going/presentation/starttrip/finishtrip/FinishTripActivity.kt
  presentation/src/main/java/com/going/presentation/starttrip/finishtrip/FinishTripViewModel.kt
  presentation/src/main/res/drawable/ic_finish_trip_copy.xml
  presentation/src/main/res/drawable/ic_finish_trip_ticket_bottom.xml
  presentation/src/main/res/drawable/ic_finish_trip_ticket_top.xml
  presentation/src/main/res/drawable/ic_finish_trip_union.xml
  presentation/src/main/res/drawable/shape_line_gray100_fill_dash_5.xml
  presentation/src/main/res/drawable/shape_line_gray100_fill_dash_5_vertical.xml
  presentation/src/main/res/layout/activity_create_trip.xml
  presentation/src/main/res/layout/activity_finish_trip.xml
  presentation/src/main/res/layout/fragment_bottom_sheet_date_content.xml
  presentation/src/main/res/layout/fragment_our_todo.xml
  presentation/src/main/res/values/strings.xml
Labels: 세연 🤤, UI 💐

#49 [UI/#44] 취향 태그 뷰 / UI 수정
  app/src/main/AndroidManifest.xml
  domain/src/main/kotlin/com/going/domain/entity/PreferenceData.kt
  presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagActivity.kt
  presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagDecoration.kt
  presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagViewHolder.kt
  presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagViewModel.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/triplist/CompletedTripFragment.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/triplist/DashBoardDecoration.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/triplist/OngoingTripFragment.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/triplist/OngoingViewHolder.kt
  presentation/src/main/res/drawable/ic_preference_tag_blur.xml
  presentation/src/main/res/drawable/ic_preference_union.xml
  presentation/src/main/res/drawable/layer_list_preference_tag_gray200_line.xml
  presentation/src/main/res/drawable/sel_radiobutton_text_color.xml
  presentation/src/main/res/drawable/sel_rounded_corner_preference_tag_button.xml
  presentation/src/main/res/drawable/shape_rect_4_white000_fill.xml
  presentation/src/main/res/layout/activity_preference_tag.xml
  presentation/src/main/res/layout/fragment_completed_trip.xml
  presentation/src/main/res/layout/item_dash_board_completed.xml
  presentation/src/main/res/layout/item_dash_board_ongoing.xml
  presentation/src/main/res/layout/item_preference_tag.xml
  presentation/src/main/res/values/strings.xml
Labels: 유빈 ❄, UI 💐

#52 [UI/#45] MyTodo / 생성화면 UI 구현
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/create/MyTodoCreateActivity.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/create/MyTodoCreateBottomSheet.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/create/MyTodoCreateViewModel.kt
  presentation/src/main/res/drawable/ic_dropdown.xml
  presentation/src/main/res/drawable/ic_lock_my_todo.xml
  presentation/src/main/res/layout/activity_my_todo_create.xml
  presentation/src/main/res/layout/fragment_my_todo_create_bottom_sheet.xml
  presentation/src/main/res/values/appearances.xml
  presentation/src/main/res/values/strings.xml
Labels: 상호 🍀, UI 💐

#53 [Feat/#41] sharedpreferences + SignIn + SignUp 분기 처리 및 연결
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/going/going/di/DataSourceModule.kt
  app/src/main/java/com/going/going/di/DataStoreModule.kt
  app/src/main/java/com/going/going/di/RepositoryModule.kt
  app/src/main/java/com/going/going/di/ServiceModule.kt
  core-ui/build.gradle.kts
  data/src/main/java/com/going/data/datasource/AuthDataSource.kt
  data/src/main/java/com/going/data/datasource/LoginDataSource.kt
  data/src/main/java/com/going/data/datasourceImpl/AuthDataSourceImpl.kt
  data/src/main/java/com/going/data/datasourceImpl/LoginDataSourceImpl.kt
  data/src/main/java/com/going/data/dto/request/RequestLoginDto.kt
  data/src/main/java/com/going/data/dto/request/SignInRequestDto.kt
  data/src/main/java/com/going/data/dto/request/SignUpRequestDto.kt
  data/src/main/java/com/going/data/dto/response/AuthResponseDto.kt
  data/src/main/java/com/going/data/dto/response/LoginResponseDto.kt
  data/src/main/java/com/going/data/local/GoingDataStore.kt
  data/src/main/java/com/going/data/local/GoingDataStoreImpl.kt
  data/src/main/java/com/going/data/repositoryImpl/AuthRepositoryImpl.kt
  data/src/main/java/com/going/data/repositoryImpl/LoginRepositoryImpl.kt
  data/src/main/java/com/going/data/repositoryImpl/TokenRepositoryImpl.kt
  data/src/main/java/com/going/data/service/AuthService.kt
  data/src/main/java/com/going/data/service/LoginService.kt
  domain/src/main/kotlin/com/going/domain/entity/request/RequestSignInModel.kt
  domain/src/main/kotlin/com/going/domain/entity/request/RequestSignUpModel.kt
  domain/src/main/kotlin/com/going/domain/repository/AuthRepository.kt
  domain/src/main/kotlin/com/going/domain/repository/LoginRepository.kt
  domain/src/main/kotlin/com/going/domain/repository/TokenRepository.kt
  presentation/src/main/java/com/going/presentation/onboarding/OnboardingProfileSettingViewModel.kt
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInState.kt
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInViewModel.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/OnboardingProfileSettingActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/OnboardingProfileSettingViewModel.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/SignUpState.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/NetworkManager.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashViewModel.kt
  presentation/src/main/java/com/going/presentation/util/JsonExt.kt
  presentation/src/main/res/layout/activity_onboarding_profile_setting.xml
Labels: 동민 🐥, FEAT ✨

#56 [UI/#54] MyTodo 조회 뷰 / UI 구현
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/going/presentation/todo/mytodo/detail/MyTodoDetailActivity.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/detail/MyTodoDetailViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoListAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoListViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoUncompleteFragment.kt
  presentation/src/main/res/layout/activity_my_todo_detail.xml
  presentation/src/main/res/values/strings.xml
Labels: 상호 🍀, UI 💐

#59 [HOTFIX/#58] 패키지네임 변경
  app/src/androidTest/java/com/going/doorip/ExampleInstrumentedTest.kt
  app/src/main/java/com/going/doorip/MyApp.kt
  app/src/main/java/com/going/doorip/di/DataSourceModule.kt
  app/src/main/java/com/going/doorip/di/DataStoreModule.kt
  app/src/main/java/com/going/doorip/di/RepositoryModule.kt
  app/src/main/java/com/going/doorip/di/RetrofitModule.kt
  app/src/main/java/com/going/doorip/di/ServiceModule.kt
  app/src/test/java/com/going/doorip/ExampleUnitTest.kt
  buildSrc/src/main/kotlin/Constants.kt
Labels: 동민 🐥, HOTFIX 🚑️

#63 [Feat/#55] token interceptor + accessToken 재발급 + token 컨트롤
  app/src/main/java/com/going/doorip/di/AuthInterceptor.kt
  app/src/main/java/com/going/doorip/di/DataSourceModule.kt
  app/src/main/java/com/going/doorip/di/DataStoreModule.kt
  app/src/main/java/com/going/doorip/di/RepositoryModule.kt
  app/src/main/java/com/going/doorip/di/RetrofitModule.kt
  app/src/main/java/com/going/doorip/di/ServiceModule.kt
  app/src/main/java/com/going/doorip/di/qualifier/RetrofitQualifier.kt
  data/src/main/java/com/going/data/datasource/SettingDataSource.kt
  data/src/main/java/com/going/data/datasourceImpl/SettingDataSourceImpl.kt
  data/src/main/java/com/going/data/dto/request/SignInRequestDto.kt
  data/src/main/java/com/going/data/dto/response/SignOutResponseDto.kt
  data/src/main/java/com/going/data/repositoryImpl/SettingRepositoryImpl.kt
  data/src/main/java/com/going/data/repositoryImpl/TokenRepositoryImpl.kt
  data/src/main/java/com/going/data/service/SettingService.kt
  domain/src/main/kotlin/com/going/domain/entity/response/SignOutModel.kt
  domain/src/main/kotlin/com/going/domain/repository/SettingRepository.kt
  domain/src/main/kotlin/com/going/domain/repository/TokenRepository.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashViewModel.kt
  presentation/src/main/java/com/going/presentation/tendencytest/result/TendencyTestResultActivity.kt
  presentation/src/main/java/com/going/presentation/util/JsonExt.kt
  presentation/src/main/res/layout/activity_tendency_test_result.xml
Labels: 동민 🐥, FEAT ✨

#65 [UI/#51] 설정 뷰 / UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/going/doorip/di/RetrofitModule.kt
  presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagActivity.kt
  presentation/src/main/java/com/going/presentation/setting/SettingActivity.kt
  presentation/src/main/java/com/going/presentation/setting/SettingLogoutDialogFragment.kt
  presentation/src/main/java/com/going/presentation/setting/SettingQuitDialogFragment.kt
  presentation/src/main/res/drawable/ic_enter_large.xml
  presentation/src/main/res/drawable/ic_unsubscribe.xml
  presentation/src/main/res/drawable/shape_rect_2_white000_fill.xml
  presentation/src/main/res/drawable/shape_rect_6_white000_fill.xml
  presentation/src/main/res/layout/activity_preference_tag.xml
  presentation/src/main/res/layout/activity_setting.xml
  presentation/src/main/res/layout/activity_trip_dash_board.xml
  presentation/src/main/res/layout/fragment_setting_logout_dialog.xml
  presentation/src/main/res/layout/fragment_setting_quit_dialog.xml
  presentation/src/main/res/layout/item_dash_board_ongoing.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
Labels: 유빈 ❄, UI 💐

#69 [Fix] errorcode 추출 방법 수정
  app/src/main/java/com/going/doorip/di/RetrofitModule.kt
  core-ui/src/main/java/com/going/ui/extension/StringExt.kt
  data/build.gradle.kts
  data/src/main/java/com/going/data/interceptor/AuthInterceptor.kt
  domain/src/main/kotlin/com/going/domain/repository/TokenRepository.kt
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashViewModel.kt
  presentation/src/main/java/com/going/presentation/tendencytest/TendencyTestSplashActivity.kt
  presentation/src/main/java/com/going/presentation/util/JsonExt.kt
  presentation/src/main/res/values/strings.xml
Labels: 동민 🐥, FIX 🔨

#67 [UI/#61] 여행 코드 입장 뷰 구현 / UI 구현
  app/src/main/AndroidManifest.xml
  domain/src/main/kotlin/com/going/domain/entity/CodeState.kt
  presentation/src/main/java/com/going/presentation/entertrip/EnterTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/EnterTripViewModel.kt
  presentation/src/main/java/com/going/presentation/starttrip/createtrip/CreateTripActivity.kt
  presentation/src/main/java/com/going/presentation/starttrip/createtrip/CreateTripViewModel.kt
  presentation/src/main/res/layout/activity_create_trip.xml
  presentation/src/main/res/layout/activity_enter_trip.xml
  presentation/src/main/res/layout/activity_start_trip_splash.xml
  presentation/src/main/res/values/strings.xml
Labels: 세연 🤤, UI 💐

#74 [FEAT/#68] 투두 전체 조회 / 서버통신 구현
  app/src/main/java/com/going/doorip/di/DataSourceModule.kt
  app/src/main/java/com/going/doorip/di/RepositoryModule.kt
  app/src/main/java/com/going/doorip/di/ServiceModule.kt
  data/src/main/java/com/going/data/datasource/TodoDataSource.kt
  data/src/main/java/com/going/data/datasourceImpl/TodoDataSourceImpl.kt
  data/src/main/java/com/going/data/dto/response/TodoResponseDto.kt
  data/src/main/java/com/going/data/interceptor/AuthInterceptor.kt
  data/src/main/java/com/going/data/repositoryImpl/TodoRepositoryImpl.kt
  data/src/main/java/com/going/data/service/TodoService.kt
  domain/src/main/kotlin/com/going/domain/entity/response/TodoAllocatorModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/TodoModel.kt
  domain/src/main/kotlin/com/going/domain/repository/TodoRepository.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoListViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoUncompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/name/TodoNameAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/name/TodoNameViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/OurTodoCreateBottomSheet.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoListViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoUncompleteFragment.kt
  presentation/src/main/res/layout/item_my_todo.xml
  presentation/src/main/res/layout/item_our_todo.xml
Labels: 상호 🍀, FEAT ✨

#76 [UI/#70] 최종 뷰 GUI 구현 완료
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/going/presentation/enter/entertrip/EnterTripActivity.kt
  presentation/src/main/java/com/going/presentation/enter/entertrip/EnterTripViewModel.kt
  presentation/src/main/java/com/going/presentation/enter/invitefinish/InviteFinishActivity.kt
  presentation/src/main/java/com/going/presentation/enter/invitefinish/InviteFinishViewModel.kt
  presentation/src/main/res/drawable/ic_finish_trip_doorips.xml
  presentation/src/main/res/drawable/ic_invite_finish_doorips.xml
  presentation/src/main/res/drawable/ic_invite_finish_letter.xml
  presentation/src/main/res/drawable/ic_start_trip_splash_doorips.xml
  presentation/src/main/res/drawable/layer_list_preference_tag_gray100_line.xml
  presentation/src/main/res/layout/activity_check_friends.xml
  presentation/src/main/res/layout/activity_create_trip.xml
  presentation/src/main/res/layout/activity_enter_trip.xml
  presentation/src/main/res/layout/activity_finish_trip.xml
  presentation/src/main/res/layout/activity_invite_finish.xml
  presentation/src/main/res/layout/activity_preference_tag.xml
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/activity_setting.xml
  presentation/src/main/res/layout/activity_start_trip_splash.xml
  presentation/src/main/res/values/strings.xml
Labels: 세연 🤤, UI 💐

#80 [Feat/#79] tendency test api 연결 및 UI 변경
  app/src/main/java/com/going/doorip/di/DataSourceModule.kt
  app/src/main/java/com/going/doorip/di/RepositoryModule.kt
  app/src/main/java/com/going/doorip/di/ServiceModule.kt
  core-ui/src/main/java/com/going/ui/extension/EnumUiState.kt
  data/src/main/java/com/going/data/datasource/SettingDataSource.kt
  data/src/main/java/com/going/data/datasource/TendencyDataSource.kt
  data/src/main/java/com/going/data/datasourceImpl/SettingDataSourceImpl.kt
  data/src/main/java/com/going/data/datasourceImpl/TendencyDataSourceImpl.kt
  data/src/main/java/com/going/data/dto/NonDataBaseResponse.kt
  data/src/main/java/com/going/data/dto/request/SignInRequestDto.kt
  data/src/main/java/com/going/data/dto/request/SignUpRequestDto.kt
  data/src/main/java/com/going/data/dto/request/TendencyRequestDto.kt
  data/src/main/java/com/going/data/dto/response/SignOutResponseDto.kt
  data/src/main/java/com/going/data/repositoryImpl/AuthRepositoryImpl.kt
  data/src/main/java/com/going/data/repositoryImpl/SettingRepositoryImpl.kt
  data/src/main/java/com/going/data/repositoryImpl/TendencyRepositoryImpl.kt
  data/src/main/java/com/going/data/service/SettingService.kt
  data/src/main/java/com/going/data/service/TendencyService.kt
  domain/src/main/kotlin/com/going/domain/entity/request/SignInRequestModel.kt
  domain/src/main/kotlin/com/going/domain/entity/request/SignUpRequestModel.kt
  domain/src/main/kotlin/com/going/domain/entity/request/TendencyRequestModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/OngoingListModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/SignOutModel.kt
  domain/src/main/kotlin/com/going/domain/repository/AuthRepository.kt
  domain/src/main/kotlin/com/going/domain/repository/SettingRepository.kt
  domain/src/main/kotlin/com/going/domain/repository/TendencyRepository.kt
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInViewModel.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/OnboardingProfileSettingViewModel.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashViewModel.kt
  presentation/src/main/java/com/going/presentation/setting/SettingLogoutDialogFragment.kt
  presentation/src/main/java/com/going/presentation/setting/SettingQuitDialogFragment.kt
  presentation/src/main/java/com/going/presentation/tendencytest/TendencyTestActivity.kt
  presentation/src/main/java/com/going/presentation/tendencytest/TendencyTestViewModel.kt
  presentation/src/main/res/drawable/img_tendency_splash.png
  presentation/src/main/res/drawable/img_tendency_test.png
  presentation/src/main/res/drawable/sel_full_button.xml
  presentation/src/main/res/layout/activity_tendency_test.xml
  presentation/src/main/res/layout/activity_tendency_test_splash.xml
  presentation/src/main/res/values/appearances.xml
  presentation/src/main/res/values/strings.xml
Labels: 동민 🐥, FEAT ✨, UI 💐

#84 [FEAT/#75] 아워, 마이 투두 조회, 생성, 삭제 / 서버통신 구현
  app/src/main/AndroidManifest.xml
  core-ui/src/main/java/com/going/ui/extension/EnumUiState.kt
  data/src/main/java/com/going/data/datasource/TodoDataSource.kt
  data/src/main/java/com/going/data/datasourceImpl/TodoDataSourceImpl.kt
  data/src/main/java/com/going/data/dto/request/TodoCreateRequestDto.kt
  data/src/main/java/com/going/data/dto/response/TodoDetailResponseDto.kt
  data/src/main/java/com/going/data/dto/response/TodoResponseDto.kt
  data/src/main/java/com/going/data/repositoryImpl/TodoRepositoryImpl.kt
  data/src/main/java/com/going/data/service/TodoService.kt
  domain/src/main/kotlin/com/going/domain/entity/request/TodoCreateRequestModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/TodoDetailModel.kt
  domain/src/main/kotlin/com/going/domain/repository/TodoRepository.kt
  presentation/src/main/java/com/going/presentation/todo/detail/PrivateDetailActivity.kt
  presentation/src/main/java/com/going/presentation/todo/detail/PrivateDetailViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/detail/PublicDetailActivity.kt
  presentation/src/main/java/com/going/presentation/todo/detail/PublicDetailViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/detail/TodoDetailNameAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/detail/TodoDetailNameViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/create/MyTodoCreateActivity.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/create/MyTodoCreateBottomSheet.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/create/MyTodoCreateViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/detail/MyTodoDetailActivity.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/detail/MyTodoDetailViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoListAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoListViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoUncompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/OurTodoCreateActivity.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/OurTodoCreateBottomSheet.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/OurTodoCreateViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/TodoCreateNameAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/TodoCreateNameViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/detail/OurTodoDetailActivity.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/detail/OurTodoDetailViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoUncompleteFragment.kt
  presentation/src/main/res/drawable/shape_rect_2_gray400_fill.xml
  presentation/src/main/res/drawable/shape_rect_2_red500_fill.xml
  presentation/src/main/res/layout/activity_private_detail.xml
  presentation/src/main/res/layout/activity_public_detail.xml
  presentation/src/main/res/layout/item_todo_create_name.xml
  presentation/src/main/res/values/strings.xml
Labels: 상호 🍀, FEAT ✨

#82 [FEAT/#77] 초대 코드 검증 API
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/going/doorip/di/DataSourceModule.kt
  app/src/main/java/com/going/doorip/di/RepositoryModule.kt
  app/src/main/java/com/going/doorip/di/ServiceModule.kt
  data/src/main/java/com/going/data/datasource/EnterTripDataSource.kt
  data/src/main/java/com/going/data/datasource/TodoDataSource.kt
  data/src/main/java/com/going/data/datasourceImpl/EnterTripDataSourceImpl.kt
  data/src/main/java/com/going/data/datasourceImpl/TodoDataSourceImpl.kt
  data/src/main/java/com/going/data/dto/request/EnterTripRequestDto.kt
  data/src/main/java/com/going/data/dto/response/EnterTripResponseDto.kt
  data/src/main/java/com/going/data/interceptor/AuthInterceptor.kt
  data/src/main/java/com/going/data/repositoryImpl/EnterTripRepositoryImpl.kt
  data/src/main/java/com/going/data/service/EnterTripService.kt
  data/src/main/java/com/going/data/service/TodoService.kt
  domain/src/main/kotlin/com/going/domain/entity/request/EnterTripRequestModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/EnterTripModel.kt
  domain/src/main/kotlin/com/going/domain/repository/EnterTripRepository.kt
  presentation/src/main/java/com/going/presentation/enter/entertrip/EnterTripActivity.kt
  presentation/src/main/java/com/going/presentation/enter/entertrip/EnterTripViewModel.kt
  presentation/src/main/java/com/going/presentation/enter/invitefinish/InviteFinishActivity.kt
  presentation/src/main/java/com/going/presentation/enter/invitefinish/InviteFinishViewModel.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/profile/ProfileActivity.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/profile/ProfileViewModel.kt
  presentation/src/main/res/layout/activity_invite_finish.xml
  presentation/src/main/res/values/strings.xml
Labels: 세연 🤤, FEAT ✨

#83 [FEAT/#73] 여행 대시 보드 뷰 / 서버 통신 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/going/doorip/di/DataSourceModule.kt
  app/src/main/java/com/going/doorip/di/RepositoryModule.kt
  app/src/main/java/com/going/doorip/di/ServiceModule.kt
  data/src/main/java/com/going/data/datasource/DashBoardDataSource.kt
  data/src/main/java/com/going/data/datasource/SettingDataSource.kt
  data/src/main/java/com/going/data/datasource/TendencyDataSource.kt
  data/src/main/java/com/going/data/datasource/TodoDataSource.kt
  data/src/main/java/com/going/data/datasourceImpl/DashBoardDataSourceImpl.kt
  data/src/main/java/com/going/data/datasourceImpl/SettingDataSourceImpl.kt
  data/src/main/java/com/going/data/datasourceImpl/TendencyDataSourceImpl.kt
  data/src/main/java/com/going/data/datasourceImpl/TodoDataSourceImpl.kt
  data/src/main/java/com/going/data/dto/NonDataBaseResponse.kt
  data/src/main/java/com/going/data/dto/response/DashBoardResponseDto.kt
  data/src/main/java/com/going/data/interceptor/AuthInterceptor.kt
  data/src/main/java/com/going/data/repositoryImpl/DashBoardRepositoryImpl.kt
  data/src/main/java/com/going/data/service/DashBoardService.kt
  data/src/main/java/com/going/data/service/SettingService.kt
  data/src/main/java/com/going/data/service/TendencyService.kt
  data/src/main/java/com/going/data/service/TodoService.kt
  domain/src/main/kotlin/com/going/domain/entity/response/CompletedListModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/DashBoardModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/OngoingListModel.kt
  domain/src/main/kotlin/com/going/domain/repository/DashBoardRepository.kt
  presentation/src/main/java/com/going/presentation/dashboard/DashBoardActivity.kt
  presentation/src/main/java/com/going/presentation/dashboard/DashBoardViewModel.kt
  presentation/src/main/java/com/going/presentation/dashboard/DashBoardViewPagerAdapter.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/CompletedAdapter.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/CompletedTripFragment.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/CompletedViewHolder.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/DashBoardDecoration.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/OngoingAdapter.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/OngoingTripFragment.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/OngoingViewHolder.kt
  presentation/src/main/java/com/going/presentation/setting/SettingActivity.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/TripDashBoardViewModel.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/triplist/CompletedTripFragment.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/triplist/OngoingTripFragment.kt
  presentation/src/main/res/drawable/ic_empty_dashboard_doorip.xml
  presentation/src/main/res/layout/activity_setting.xml
  presentation/src/main/res/layout/activity_trip_dash_board.xml
  presentation/src/main/res/layout/fragment_completed_trip.xml
  presentation/src/main/res/layout/fragment_ongoing_trip.xml
  presentation/src/main/res/values/strings.xml
Labels: 유빈 ❄, FEAT ✨

#88 [FEAT/#85] 아워투두, 마이투두 정보 / 서버통신 구현
  data/src/main/java/com/going/data/datasource/SettingDataSource.kt
  data/src/main/java/com/going/data/datasource/TendencyDataSource.kt
  data/src/main/java/com/going/data/datasource/TodoDataSource.kt
  data/src/main/java/com/going/data/datasourceImpl/SettingDataSourceImpl.kt
  data/src/main/java/com/going/data/datasourceImpl/TendencyDataSourceImpl.kt
  data/src/main/java/com/going/data/datasourceImpl/TodoDataSourceImpl.kt
  data/src/main/java/com/going/data/dto/NonDataBaseResponse.kt
  data/src/main/java/com/going/data/dto/response/MyTripInfoResponseDto.kt
  data/src/main/java/com/going/data/dto/response/OurTripInfoResponseDto.kt
  data/src/main/java/com/going/data/dto/response/TodoAllocatorResponseDto.kt
  data/src/main/java/com/going/data/dto/response/TodoDetailResponseDto.kt
  data/src/main/java/com/going/data/dto/response/TodoResponseDto.kt
  data/src/main/java/com/going/data/dto/response/TripParticipantResponseDto.kt
  data/src/main/java/com/going/data/interceptor/AuthInterceptor.kt
  data/src/main/java/com/going/data/repositoryImpl/TodoRepositoryImpl.kt
  data/src/main/java/com/going/data/service/SettingService.kt
  data/src/main/java/com/going/data/service/TendencyService.kt
  data/src/main/java/com/going/data/service/TodoService.kt
  domain/src/main/kotlin/com/going/domain/entity/response/MyTripInfoModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/OurTripInfoModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/TripParticipantModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/TripParticipantsListModel.kt
  domain/src/main/kotlin/com/going/domain/repository/TodoRepository.kt
  presentation/src/main/java/com/going/presentation/checkfriends/CheckFriendsViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/create/MyTodoCreateViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFriendAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFriendViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/OurTodoCreateViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/TodoCreateNameAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/TodoCreateNameViewHolder.kt
  presentation/src/main/res/layout/fragment_our_todo.xml
  presentation/src/main/res/values/strings.xml
Labels: 상호 🍀, FEAT ✨

#90 [Feat/#81] splash api 연결 및 tendency result api / UI 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/going/doorip/di/DataSourceModule.kt
  app/src/main/java/com/going/doorip/di/RepositoryModule.kt
  app/src/main/java/com/going/doorip/di/ServiceModule.kt
  data/src/main/java/com/going/data/datasource/AuthDataSource.kt
  data/src/main/java/com/going/data/datasource/ProfileDataSource.kt
  data/src/main/java/com/going/data/datasourceImpl/AuthDataSourceImpl.kt
  data/src/main/java/com/going/data/datasourceImpl/ProfileDataSourceImpl.kt
  data/src/main/java/com/going/data/dto/response/UserProfileResponseDto.kt
  data/src/main/java/com/going/data/repositoryImpl/AuthRepositoryImpl.kt
  data/src/main/java/com/going/data/repositoryImpl/ProfileRepositoryImpl.kt
  data/src/main/java/com/going/data/service/AuthService.kt
  data/src/main/java/com/going/data/service/ProfileService.kt
  domain/src/main/kotlin/com/going/domain/entity/AuthState.kt
  domain/src/main/kotlin/com/going/domain/entity/ProfileMock.kt
  domain/src/main/kotlin/com/going/domain/entity/request/UserProfileRequestModel.kt
  domain/src/main/kotlin/com/going/domain/repository/AuthRepository.kt
  domain/src/main/kotlin/com/going/domain/repository/ProfileRepository.kt
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInState.kt
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInViewModel.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/OnboardingProfileSettingActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/OnboardingProfileSettingViewModel.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/SignUpState.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashViewModel.kt
  presentation/src/main/java/com/going/presentation/setting/SettingQuitDialogFragment.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultViewModel.kt
  presentation/src/main/java/com/going/presentation/tendency/splash/TendencySplashActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/ttest/TendencyTestActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/ttest/TendencyTestViewModel.kt
  presentation/src/main/java/com/going/presentation/tendencytest/result/TendencyTestResultActivity.kt
  presentation/src/main/java/com/going/presentation/tendencytest/result/TendencyTestResultViewModel.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/profile/ProfileViewModel.kt
  presentation/src/main/res/drawable/ic_download.xml
  presentation/src/main/res/drawable/img_tendency_result_aei.png
  presentation/src/main/res/drawable/img_tendency_result_aep.png
  presentation/src/main/res/drawable/img_tendency_result_ari.png
  presentation/src/main/res/drawable/img_tendency_result_arp.png
  presentation/src/main/res/drawable/img_tendency_result_sei.png
  presentation/src/main/res/drawable/img_tendency_result_sep.png
  presentation/src/main/res/drawable/img_tendency_result_sri.png
  presentation/src/main/res/drawable/img_tendency_result_srp.png
  presentation/src/main/res/drawable/shape_rect_top8_white000_fill.xml
  presentation/src/main/res/layout/activity_tendency_result.xml
  presentation/src/main/res/layout/activity_tendency_splash.xml
  presentation/src/main/res/layout/activity_tendency_test.xml
  presentation/src/main/res/values/strings.xml
Labels: 동민 🐥, FEAT ✨

#91 [FEAT/#86] 여행 생성 뷰
  presentation/src/main/java/com/going/presentation/enter/FinishPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/starttrip/createtrip/CreateTripActivity.kt
  presentation/src/main/res/layout/activity_finish_preference.xml
Labels: 세연 🤤, FEAT ✨

#97 [FEAT/#89] MyTodo 미완료, 완료 / 서버통신 구현
  data/src/main/java/com/going/data/datasource/TodoDataSource.kt
  data/src/main/java/com/going/data/datasourceImpl/TodoDataSourceImpl.kt
  data/src/main/java/com/going/data/repositoryImpl/TodoRepositoryImpl.kt
  data/src/main/java/com/going/data/service/TodoService.kt
  domain/src/main/kotlin/com/going/domain/entity/response/TripParticipantModel.kt
  domain/src/main/kotlin/com/going/domain/repository/TodoRepository.kt
  presentation/src/main/java/com/going/presentation/todo/TodoActivity.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoListAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoListViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoUncompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/OurTodoCreateActivity.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/OurTodoCreateViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/TodoCreateNameAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/TodoCreateNameViewHolder.kt
  presentation/src/main/res/layout/fragment_my_todo.xml
  presentation/src/main/res/layout/fragment_our_todo.xml
Labels: 상호 🍀, FEAT ✨

#99 [Feat/#93] image download 기능 구현
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultViewModel.kt
  presentation/src/main/java/com/going/presentation/tendency/ttest/TendencyTestActivity.kt
  presentation/src/main/res/values/strings.xml
Labels: 동민 🐥, FEAT ✨

#101 [UI/#98] OurTodo, MyTodo / 최종 GUI 구현
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFriendViewHolder.kt
  presentation/src/main/res/drawable/ic_mytodo_disabled.xml
  presentation/src/main/res/drawable/ic_mytodo_enabled.xml
  presentation/src/main/res/drawable/ic_mytodo_selected.xml
  presentation/src/main/res/drawable/ic_mytodo_unselected.xml
  presentation/src/main/res/drawable/ic_ourtodo_disabled.xml
  presentation/src/main/res/drawable/ic_ourtodo_enabled.xml
  presentation/src/main/res/drawable/ic_ourtodo_selected.xml
  presentation/src/main/res/drawable/ic_ourtodo_unselected.xml
  presentation/src/main/res/drawable/ic_profile.xml
  presentation/src/main/res/drawable/ic_todo_friend.png
  presentation/src/main/res/drawable/img_mytodo_main.xml
  presentation/src/main/res/drawable/img_ourtodo_main.xml
  presentation/src/main/res/drawable/img_profile_1.xml
  presentation/src/main/res/drawable/img_profile_2.xml
  presentation/src/main/res/drawable/img_profile_3.xml
  presentation/src/main/res/drawable/img_profile_4.xml
  presentation/src/main/res/drawable/img_profile_5.xml
  presentation/src/main/res/drawable/img_profile_6.xml
  presentation/src/main/res/drawable/img_profile_7.xml
  presentation/src/main/res/drawable/img_profile_8.xml
  presentation/src/main/res/drawable/sel_bnv_icon_my_todo.xml
  presentation/src/main/res/drawable/sel_bnv_icon_our_todo.xml
  presentation/src/main/res/layout/activity_my_todo_create.xml
  presentation/src/main/res/layout/fragment_my_todo.xml
  presentation/src/main/res/layout/fragment_our_todo.xml
  presentation/src/main/res/layout/item_todo_friends.xml
  presentation/src/main/res/values/strings.xml
Labels: 상호 🍀, UI 💐

#103 [Fix/#94] 오류 수정 및 setting 링크 연결
  .idea/git_toolbox_prj.xml
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInViewModel.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/OnboardingProfileSettingActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/OnboardingProfileSettingViewModel.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashViewModel.kt
  presentation/src/main/java/com/going/presentation/setting/SettingActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultViewModel.kt
  presentation/src/main/java/com/going/presentation/tendency/ttest/TendencyTestActivity.kt
  presentation/src/main/res/drawable/img_sign_in_kakao_button.png
  presentation/src/main/res/layout/activity_setting.xml
  presentation/src/main/res/layout/activity_signin.xml
  presentation/src/main/res/values/strings.xml
Labels: 동민 🐥, FEAT ✨, FIX 🔨

#104 [FEAT]/#92 여행 입장 뷰 / 서버통신 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/going/doorip/di/DataSourceModule.kt
  app/src/main/java/com/going/doorip/di/RepositoryModule.kt
  app/src/main/java/com/going/doorip/di/ServiceModule.kt
  data/src/main/java/com/going/data/datasource/StartInviteTripDataSource.kt
  data/src/main/java/com/going/data/datasourceImpl/StartInviteTripDataSourceImpl.kt
  data/src/main/java/com/going/data/dto/request/StartInviteTripRequestDto.kt
  data/src/main/java/com/going/data/dto/response/StartInviteTripResponseDto.kt
  data/src/main/java/com/going/data/interceptor/AuthInterceptor.kt
  data/src/main/java/com/going/data/repositoryImpl/StartInviteTripRepositoryImpl.kt
  data/src/main/java/com/going/data/service/StartInviteTripService.kt
  domain/src/main/kotlin/com/going/domain/entity/request/StartInviteTripRequestModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/StartInviteTripModel.kt
  domain/src/main/kotlin/com/going/domain/repository/StartInviteTripRepository.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/StartTripSplashActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/createtrip/BottomSheetDateContentFragment.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/createtrip/EnterPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/createtrip/EnterTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/createtrip/EnterTripViewModel.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/createtrip/FinishTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/createtrip/FinishTripViewModel.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/invitetrip/CreateTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/invitetrip/CreateTripViewModel.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/invitetrip/FinishPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/invitetrip/FinishPreferenceViewModel.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/invitetrip/InviteFinishActivity.kt
  presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagViewModel.kt
  presentation/src/main/java/com/going/presentation/preferencetag/invitefinish/FinishPreferenceActivity.kt
  presentation/src/main/res/layout/activity_create_trip.xml
  presentation/src/main/res/layout/activity_enter_preference.xml
  presentation/src/main/res/layout/activity_enter_trip.xml
  presentation/src/main/res/layout/activity_finish_preference.xml
  presentation/src/main/res/layout/activity_finish_trip.xml
  presentation/src/main/res/layout/activity_invite_finish.xml
Labels: 세연 🤤, FEAT ✨

#108 [FEAT/#96] 여행 생성 뷰 / 서버 통신 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/going/doorip/di/DataSourceModule.kt
  app/src/main/java/com/going/doorip/di/RepositoryModule.kt
  app/src/main/java/com/going/doorip/di/ServiceModule.kt
  data/src/main/java/com/going/data/datasource/EnterPreferenceDataSource.kt
  data/src/main/java/com/going/data/datasourceImpl/DashBoardDataSourceImpl.kt
  data/src/main/java/com/going/data/datasourceImpl/EnterPreferenceDataSourceImpl.kt
  data/src/main/java/com/going/data/dto/interceptor/AuthInterceptor.kt
  data/src/main/java/com/going/data/dto/request/EnterPreferenceRequestDto.kt
  data/src/main/java/com/going/data/dto/request/EnterTripRequestDto.kt
  data/src/main/java/com/going/data/dto/response/EnterPreferenceResponseDto.kt
  data/src/main/java/com/going/data/repositoryImpl/EnterPreferenceRepositoryImpl.kt
  data/src/main/java/com/going/data/service/EnterPreferenceService.kt
  domain/src/main/kotlin/com/going/domain/entity/request/EnterPreferenceRequestModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/EnterPreferenceModel.kt
  domain/src/main/kotlin/com/going/domain/repository/EnterPreferenceRepository.kt
  presentation/src/main/java/com/going/presentation/dashboard/DashBoardActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/createtrip/BottomSheetDateContentFragment.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/createtrip/EnterPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/createtrip/EnterPreferenceViewModel.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/createtrip/EnterTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/createtrip/FinishTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/createtrip/FinishTripViewModel.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/invitetrip/CreateTripViewModel.kt
  presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagAdapter.kt
  presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagDecoration.kt
  presentation/src/main/res/drawable/sel_button_text_color_preference.xml
  presentation/src/main/res/layout/activity_enter_preference.xml
  presentation/src/main/res/layout/activity_finish_preference.xml
  presentation/src/main/res/layout/activity_finish_trip.xml
  presentation/src/main/res/values/strings.xml
Labels: 유빈 ❄, FEAT ✨

#106 [Hotfix/#105] auth dto 핫픽스
  data/src/main/java/com/going/data/dto/interceptor/AuthInterceptor.kt
  data/src/main/java/com/going/data/dto/response/AuthResponseDto.kt
  data/src/main/java/com/going/data/dto/response/SignInResponseDto.kt
  data/src/main/java/com/going/data/local/GoingDataStore.kt
  data/src/main/java/com/going/data/local/GoingDataStoreImpl.kt
  data/src/main/java/com/going/data/repositoryImpl/TokenRepositoryImpl.kt
  domain/src/main/kotlin/com/going/domain/entity/response/AuthTokenModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/SignInModel.kt
  domain/src/main/kotlin/com/going/domain/repository/TokenRepository.kt
  presentation/src/main/java/com/going/presentation/dashboard/DashBoardActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/createtrip/EnterTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/starttrip/invitetrip/CreateTripActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInViewModel.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/OnboardingProfileSettingActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/OnboardingProfileSettingViewModel.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashViewModel.kt
  presentation/src/main/java/com/going/presentation/setting/SettingActivity.kt
  presentation/src/main/java/com/going/presentation/setting/SettingViewModel.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/splash/TendencySplashActivity.kt
  presentation/src/main/res/layout/activity_onboarding_profile_setting.xml
  presentation/src/main/res/layout/activity_tendency_result.xml
  presentation/src/main/res/layout/activity_trip_dash_board.xml
Labels: HOTFIX 🚑️

#107 [FEAT/#102] OurTodo / 초대코드 다이얼로그 구현
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/invite/FriendInviteDialog.kt
  presentation/src/main/res/layout/activity_finish_trip.xml
  presentation/src/main/res/layout/fragment_friend_invite_dialog.xml
  presentation/src/main/res/values/strings.xml
Labels: 상호 🍀, FEAT ✨

#115 [Add/#113] download image 추가 및 텍스트 수정
  domain/src/main/kotlin/com/going/domain/entity/ProfileMock.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/preference/EnterPreferenceViewModel.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/preference/FinishPreferenceViewModel.kt
  presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagViewModel.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultViewModel.kt
  presentation/src/main/java/com/going/presentation/tendency/ttest/TendencyTestViewModel.kt
  presentation/src/main/java/com/going/presentation/tripdashboard/profile/ProfileViewModel.kt
  presentation/src/main/res/drawable/img_download_aei.png
  presentation/src/main/res/drawable/img_download_aep.png
  presentation/src/main/res/drawable/img_download_ari.png
  presentation/src/main/res/drawable/img_download_arp.png
  presentation/src/main/res/drawable/img_download_sei.png
  presentation/src/main/res/drawable/img_download_sep.png
  presentation/src/main/res/drawable/img_download_sri.png
  presentation/src/main/res/drawable/img_download_srp.png
Labels: 동민 🐥, ADD ➕

#116 [MOVE/#110] 유빈 담당 뷰 / 패키지 재구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/going/doorip/di/DataSourceModule.kt
  app/src/main/java/com/going/doorip/di/RepositoryModule.kt
  app/src/main/java/com/going/doorip/di/ServiceModule.kt
  data/src/main/java/com/going/data/datasource/EnterPreferenceDataSource.kt
  data/src/main/java/com/going/data/datasource/EnterTripDataSource.kt
  data/src/main/java/com/going/data/datasourceImpl/EnterPreferenceDataSourceImpl.kt
  data/src/main/java/com/going/data/datasourceImpl/EnterTripDataSourceImpl.kt
  data/src/main/java/com/going/data/repositoryImpl/EnterPreferenceRepositoryImpl.kt
  data/src/main/java/com/going/data/repositoryImpl/EnterTripRepositoryImpl.kt
  data/src/main/java/com/going/data/service/EnterPreferenceService.kt
  data/src/main/java/com/going/data/service/EnterTripService.kt
  domain/src/main/kotlin/com/going/domain/repository/EnterPreferenceRepository.kt
  domain/src/main/kotlin/com/going/domain/repository/EnterTripRepository.kt
  presentation/src/main/java/com/going/presentation/dashboard/DashBoardActivity.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/completed/CompletedTripFragment.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/ongoing/OngoingTripFragment.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/preference/EnterPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/preference/EnterPreferenceViewModel.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/preference/FinishPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/preferencetag/PreferenceTagAdapter.kt
  presentation/src/main/java/com/going/presentation/entertrip/preferencetag/PreferenceTagDecoration.kt
  presentation/src/main/java/com/going/presentation/entertrip/preferencetag/PreferenceTagViewHolder.kt
  presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/checkfriends/CheckFriendsActivity.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/checkfriends/CheckFriendsViewModel.kt
  presentation/src/main/res/drawable/layer_list_trip_friends_progress_bar.xml
  presentation/src/main/res/layout/activity_check_friends.xml
Labels: 유빈 ❄, FEAT ✨, MOVE 🚚

#119 [FIX/#118] 여행 대시 보드 뷰 / Empty 뷰 구현
  presentation/src/main/java/com/going/presentation/dashboard/DashBoardViewModel.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/completed/CompletedTripFragment.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/ongoing/OngoingTripFragment.kt
  presentation/src/main/res/layout/fragment_completed_trip.xml
  presentation/src/main/res/layout/fragment_ongoing_trip.xml
Labels: 유빈 ❄, FIX 🔨

#120 [FEAT/#111] 액티비티 간 navigation 연결
  app/src/main/AndroidManifest.xml
  buildSrc/src/main/kotlin/Constants.kt
  data/src/main/java/com/going/data/dto/response/MyTripInfoResponseDto.kt
  domain/src/main/kotlin/com/going/domain/entity/response/MyTripInfoModel.kt
  presentation/src/main/java/com/going/presentation/dashboard/DashBoardActivity.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/completed/CompletedTripFragment.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/ongoing/OngoingTripFragment.kt
  presentation/src/main/java/com/going/presentation/entertrip/StartTripSplashActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/choosedate/EnterTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/finish/FinishTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/preference/EnterPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/finish/InviteFinishActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/invitecode/CreateTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/preference/FinishPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/OnboardingProfileSettingActivity.kt
  presentation/src/main/java/com/going/presentation/profile/ProfileActivity.kt
  presentation/src/main/java/com/going/presentation/profile/ProfileViewModel.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/splash/TendencySplashActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/ttest/TendencyTestActivity.kt
  presentation/src/main/java/com/going/presentation/todo/TodoActivity.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/create/MyTodoCreateActivity.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/create/MyTodoCreateViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoUncompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/OurTodoCreateActivity.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/OurTodoCreateViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoUncompleteFragment.kt
  presentation/src/main/res/layout/activity_create_trip.xml
  presentation/src/main/res/layout/activity_enter_preference.xml
  presentation/src/main/res/layout/activity_finish_preference.xml
  presentation/src/main/res/layout/activity_finish_trip.xml
  presentation/src/main/res/layout/activity_invite_finish.xml
  presentation/src/main/res/values/strings.xml
Labels: 상호 🍀, FEAT ✨

#122 [CHORE/#121] version code 6 변경
  buildSrc/src/main/kotlin/Constants.kt
Labels: 상호 🍀, CHORE 🎀

#125 [FEAT/#114] 프로필 조회 뷰 / 서버통신 구현
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/going/presentation/dashboard/triplist/ongoing/OngoingTripFragment.kt
  presentation/src/main/java/com/going/presentation/entertrip/StartTripSplashActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/choosedate/BottomSheetDateContentFragment.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/choosedate/CreateTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/choosedate/CreateTripViewModel.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/finish/FinishTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/preference/EnterPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/finish/InviteFinishActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/invitecode/EnterTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/invitecode/EnterTripViewModel.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/preference/FinishPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/profile/ProfileActivity.kt
  presentation/src/main/java/com/going/presentation/profile/ProfileViewModel.kt
  presentation/src/main/java/com/going/presentation/setting/SettingActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultViewModel.kt
  presentation/src/main/res/layout/activity_create_trip.xml
  presentation/src/main/res/layout/activity_enter_trip.xml
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/fragment_bottom_sheet_date_content.xml
  presentation/src/main/res/values/strings.xml
Labels: 세연 🤤, FEAT ✨

#131 [FEAT/#130] 마이 투두 뷰 / 로직 수정
  data/src/main/java/com/going/data/dto/interceptor/AuthInterceptor.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/ongoing/OngoingTripFragment.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoFragment.kt
Labels: 유빈 ❄, FEAT ✨

#127 [Fix/#124] JWT 토큰 재발급 로직 수정
  .idea/git_toolbox_prj.xml
  app/src/main/java/com/going/doorip/di/DataSourceModule.kt
  app/src/main/java/com/going/doorip/di/RepositoryModule.kt
  app/src/main/java/com/going/doorip/di/RetrofitModule.kt
  app/src/main/java/com/going/doorip/di/ServiceModule.kt
  app/src/main/java/com/going/doorip/di/qualifier/RetrofitQualifier.kt
  data/src/main/java/com/going/data/datasource/TokenReissueDataSource.kt
  data/src/main/java/com/going/data/datasourceImpl/TokenReissueDataSourceImpl.kt
  data/src/main/java/com/going/data/dto/interceptor/AuthInterceptor.kt
  data/src/main/java/com/going/data/dto/request/TokenReissueRequestDto.kt
  data/src/main/java/com/going/data/interceptor/AuthInterceptor.kt
  data/src/main/java/com/going/data/repositoryImpl/TokenReissueRepositoryImpl.kt
  data/src/main/java/com/going/data/service/DashBoardService.kt
  data/src/main/java/com/going/data/service/TokenReissueService.kt
  domain/src/main/kotlin/com/going/domain/entity/request/TokenReissueRequestModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/EnterPreferenceModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/TokenReissueModel.kt
  domain/src/main/kotlin/com/going/domain/repository/TokenReissueRepository.kt
  presentation/src/main/java/com/going/presentation/dashboard/DashBoardViewModel.kt
Labels: 동민 🐥, FIX 🔨

#132 [UI/#114] 여행 입장 뷰 / 토스트 위치 수정
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/choosedate/BottomSheetDateContentFragment.kt
  presentation/src/main/res/drawable/shape_rect_4_gray700_fill.xml
  presentation/src/main/res/drawable/shape_rect_4_white000_fill.xml
  presentation/src/main/res/drawable/shape_rect_top40_white000_fill.xml
  presentation/src/main/res/drawable/shape_rect_top4_white000_fill.xml
  presentation/src/main/res/layout/fragment_bottom_sheet_date_content.xml
  presentation/src/main/res/layout/fragment_my_todo_create_bottom_sheet.xml
  presentation/src/main/res/layout/fragment_our_todo_create_bottom_sheet.xml
Labels: 세연 🤤, UI 💐

#134 [FEAT/#123] OurTodo, MyTodo / EmptyView 구현
  app/src/main/AndroidManifest.xml
  core-ui/src/main/java/com/going/ui/extension/ActivityExt.kt
  core-ui/src/main/java/com/going/ui/extension/FragmentExt.kt
  data/src/main/java/com/going/data/datasource/TendencyDataSource.kt
  data/src/main/java/com/going/data/datasourceImpl/AuthDataSourceImpl.kt
  data/src/main/java/com/going/data/datasourceImpl/MockDataSourceImpl.kt
  data/src/main/java/com/going/data/datasourceImpl/SettingDataSourceImpl.kt
  data/src/main/java/com/going/data/repositoryImpl/AuthRepositoryImpl.kt
  data/src/main/java/com/going/data/repositoryImpl/EnterTripRepositoryImpl.kt
  data/src/main/java/com/going/data/repositoryImpl/MockRepositoryImpl.kt
  data/src/main/java/com/going/data/repositoryImpl/ProfileRepositoryImpl.kt
  data/src/main/java/com/going/data/repositoryImpl/SettingRepositoryImpl.kt
  domain/src/main/kotlin/com/going/domain/repository/EnterTripRepository.kt
  domain/src/main/kotlin/com/going/domain/repository/TendencyRepository.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
  presentation/src/main/java/com/going/presentation/todo/TodoActivity.kt
  presentation/src/main/java/com/going/presentation/todo/TodoDecoration.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoUncompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoUncompleteFragment.kt
  presentation/src/main/res/drawable/img_mytodo_empty.xml
  presentation/src/main/res/drawable/img_ourtodo_empty.xml
  presentation/src/main/res/layout/fragment_my_todo.xml
  presentation/src/main/res/layout/fragment_my_todo_complete.xml
  presentation/src/main/res/layout/fragment_my_todo_uncomplete.xml
  presentation/src/main/res/layout/fragment_our_todo.xml
  presentation/src/main/res/layout/fragment_our_todo_complete.xml
  presentation/src/main/res/layout/fragment_our_todo_uncomplete.xml
  presentation/src/main/res/values/strings.xml
Labels: 상호 🍀, FEAT ✨

#136 [REFACTOR/#129] 익스텐션 분리 및 전체적인 QA 후 수정
  core-ui/src/main/java/com/going/ui/extension/ActivityExt.kt
  core-ui/src/main/java/com/going/ui/extension/FragmentExt.kt
  core-ui/src/main/java/com/going/ui/extension/StringExt.kt
  domain/src/main/kotlin/com/going/domain/entity/ProfileMock.kt
  presentation/src/main/java/com/going/presentation/dashboard/DashBoardActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/StartTripSplashActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/choosedate/CreateTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/choosedate/CreateTripViewModel.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/finish/FinishTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/preference/EnterPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/preference/FinishPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/OnboardingProfileSettingActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/OnboardingProfileSettingViewModel.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
  presentation/src/main/java/com/going/presentation/profile/ProfileActivity.kt
  presentation/src/main/java/com/going/presentation/profile/ProfileViewModel.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultViewModel.kt
  presentation/src/main/java/com/going/presentation/tendency/result/UserTendencyResultList.kt
  presentation/src/main/java/com/going/presentation/tendency/splash/TendencySplashActivity.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/create/MyTodoCreateViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/OurTodoCreateViewModel.kt
  presentation/src/main/java/com/going/presentation/util/ActivityExt.kt
  presentation/src/main/res/drawable/ic_start_trip_splash_doorips.xml
  presentation/src/main/res/drawable/img_start_trip_splash.png
  presentation/src/main/res/layout/activity_create_trip.xml
  presentation/src/main/res/layout/activity_enter_preference.xml
  presentation/src/main/res/layout/activity_finish_preference.xml
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/activity_setting.xml
  presentation/src/main/res/layout/activity_start_trip_splash.xml
  presentation/src/main/res/layout/activity_tendency_result.xml
  presentation/src/main/res/values/strings.xml
Labels: 동민 🐥, REFACTOR ♻️

#138 [FIX/#135] OurTodo, MyTodo / ListAdapter 관련 이슈 대응
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoListAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoUncompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoListAdapter.kt
Labels: 상호 🍀, FIX 🔨

#141 [FIX/#139] 폰트 대응
  presentation/src/main/java/com/going/presentation/tendency/ttest/TendencyTestActivity.kt
  presentation/src/main/res/drawable/shape_rect_8_red500_line_white000_fill.xml
  presentation/src/main/res/layout/activity_onboarding_profile_setting.xml
  presentation/src/main/res/layout/activity_tendency_result.xml
  presentation/src/main/res/layout/activity_tendency_test.xml
Labels: 동민 🐥, FIX 🔨

#142 [FIX/#137] 유빈 담당 뷰 / 이슈 대응
  presentation/src/main/java/com/going/presentation/dashboard/triplist/completed/CompletedViewHolder.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/ongoing/OngoingViewHolder.kt
  presentation/src/main/res/layout/activity_check_friends.xml
  presentation/src/main/res/layout/activity_setting.xml
  presentation/src/main/res/layout/activity_trip_dash_board.xml
  presentation/src/main/res/layout/fragment_completed_trip.xml
  presentation/src/main/res/layout/fragment_ongoing_trip.xml
  presentation/src/main/res/layout/item_dash_board_completed.xml
  presentation/src/main/res/layout/item_dash_board_ongoing.xml
  presentation/src/main/res/layout/item_preference_tag.xml
  presentation/src/main/res/values/strings.xml
Labels: 유빈 ❄, FIX 🔨

#147 [FIX/#140] OurTodo, MyTodo / 투두 스티키 헤더 상태에 따른 탭바 색상 전환
  domain/src/main/kotlin/com/going/domain/entity/CodeState.kt
  domain/src/main/kotlin/com/going/domain/entity/PreferenceData.kt
  domain/src/main/kotlin/com/going/domain/entity/request/EnterPreferenceRequestModel.kt
  domain/src/main/kotlin/com/going/domain/entity/request/TodoCreateRequestModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/CheckFriendsModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/DashBoardModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/MockFollowerModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/MyTripInfoModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/OurTripInfoModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/TodoAllocatorModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/TodoDetailModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/TodoModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/TripParticipantModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/TripParticipantsListModel.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/invitecode/EnterTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/invitecode/EnterTripViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/res/layout/fragment_friend_invite_dialog.xml
  presentation/src/main/res/layout/fragment_our_todo.xml
  presentation/src/main/res/layout/fragment_our_todo_complete.xml
  presentation/src/main/res/layout/fragment_our_todo_uncomplete.xml
  presentation/src/main/res/layout/item_my_todo.xml
  presentation/src/main/res/layout/item_our_todo.xml
  presentation/src/main/res/layout/item_todo_friends.xml
  presentation/src/main/res/values/strings.xml
Labels: 상호 🍀, FIX 🔨

#150 [FIX/#145] QA 이슈 대응
  presentation/src/main/java/com/going/presentation/dashboard/DashBoardActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/preference/EnterPreferenceViewModel.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/preference/FinishPreferenceViewModel.kt
  presentation/src/main/java/com/going/presentation/tendency/result/UserTendencyResultList.kt
  presentation/src/main/java/com/going/presentation/tendency/ttest/TendencyTestViewModel.kt
  presentation/src/main/res/drawable/sel_rounded_corner_button.xml
  presentation/src/main/res/drawable/shape_rect_6_gray200_line.xml
  presentation/src/main/res/drawable/shape_rect_6_white000_fill_gray200_line.xml
  presentation/src/main/res/layout/activity_check_friends.xml
  presentation/src/main/res/layout/activity_enter_preference.xml
  presentation/src/main/res/layout/activity_onboarding_profile_setting.xml
  presentation/src/main/res/layout/activity_setting.xml
  presentation/src/main/res/layout/activity_tendency_result.xml
  presentation/src/main/res/layout/activity_trip_dash_board.xml
  presentation/src/main/res/values/strings.xml
Labels: 유빈 ❄, FIX 🔨

#151 [Fix/149] QA 반영
  app/src/main/AndroidManifest.xml
  domain/src/main/kotlin/com/going/domain/entity/NameState.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/choosedate/CreateTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/choosedate/CreateTripViewModel.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/OnboardingProfileSettingActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/OnboardingProfileSettingViewModel.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/create/MyTodoCreateActivity.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/create/MyTodoCreateViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/OurTodoCreateActivity.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/OurTodoCreateViewModel.kt
  presentation/src/main/java/com/going/presentation/util/ActivityExt.kt
  presentation/src/main/res/drawable/ic_kakao.xml
  presentation/src/main/res/drawable/shape_kakao_yellow_fill_8_rect.xml
  presentation/src/main/res/layout/activity_create_trip.xml
  presentation/src/main/res/layout/activity_my_todo_create.xml
  presentation/src/main/res/layout/activity_onboarding_profile_setting.xml
  presentation/src/main/res/layout/activity_our_todo_create.xml
  presentation/src/main/res/layout/activity_signin.xml
  presentation/src/main/res/values/strings.xml
Labels: 동민 🐥, FIX 🔨

#154 [FIX/#148] OurTodo, MyTodo / QA 이슈 대응, Empty뷰 위치 설정
  core-ui/src/main/java/com/going/ui/extension/ActivityExt.kt
  presentation/src/main/java/com/going/presentation/dashboard/DashBoardActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/finish/FinishTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/preference/EnterPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/preference/FinishPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/todo/TodoActivity.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoUncompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFriendViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoUncompleteFragment.kt
  presentation/src/main/res/layout/activity_private_detail.xml
  presentation/src/main/res/layout/fragment_my_todo_complete.xml
  presentation/src/main/res/layout/fragment_my_todo_uncomplete.xml
  presentation/src/main/res/layout/fragment_our_todo.xml
  presentation/src/main/res/layout/fragment_our_todo_complete.xml
  presentation/src/main/res/layout/fragment_our_todo_uncomplete.xml
Labels: 상호 🍀, FEAT ✨

#153 [FIX/#152] QA 이슈 대응
  presentation/src/main/java/com/going/presentation/entertrip/preferencetag/PreferenceTagViewHolder.kt
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/activity_tendency_result.xml
  presentation/src/main/res/layout/activity_trip_dash_board.xml
  presentation/src/main/res/layout/item_dash_board_completed.xml
  presentation/src/main/res/layout/item_dash_board_ongoing.xml
  presentation/src/main/res/layout/item_preference_tag.xml
  presentation/src/main/res/values/strings.xml
Labels: 유빈 ❄, FIX 🔨

#157 [FIX/#144] 세연 담당 뷰 / QA 이슈 해결
  core-ui/src/main/java/com/going/ui/base/BaseBottomSheet.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/choosedate/BottomSheetDateContentFragment.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/finish/FinishTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/finish/InviteFinishActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/invitecode/EnterTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/invitecode/EnterTripViewModel.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/preference/FinishPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/preference/FinishPreferenceViewModel.kt
  presentation/src/main/java/com/going/presentation/tendency/result/UserTendencyResultList.kt
  presentation/src/main/res/drawable/shape_rect_6_gray100_line.xml
  presentation/src/main/res/layout/activity_create_trip.xml
  presentation/src/main/res/layout/activity_enter_trip.xml
  presentation/src/main/res/layout/activity_finish_trip.xml
  presentation/src/main/res/layout/activity_invite_finish.xml
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/fragment_bottom_sheet_date_content.xml
  presentation/src/main/res/values/strings.xml
Labels: 세연 🤤, FIX 🔨

#160 [FIX/#158] 6명 초과 서버통신 구현
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/preference/FinishPreferenceActivity.kt
Labels: 세연 🤤, FEAT ✨

#159 [FIX/#156] 로티 추가 및 카카오 버튼 수정
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoCompleteFragment.kt
  presentation/src/main/res/layout/activity_signin.xml
  presentation/src/main/res/layout/activity_splash.xml
  presentation/src/main/res/raw/doorip_splash.json
Labels: 동민 🐥, ADD ➕, FIX 🔨

#161 [FIX/#155] OurTodo, MyTodo / Empty 뷰 parent fragment로 이동
  buildSrc/src/main/kotlin/Constants.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoUncompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFriendAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoUncompleteFragment.kt
  presentation/src/main/res/layout/fragment_my_todo.xml
  presentation/src/main/res/layout/fragment_my_todo_complete.xml
  presentation/src/main/res/layout/fragment_my_todo_uncomplete.xml
  presentation/src/main/res/layout/fragment_our_todo.xml
  presentation/src/main/res/layout/fragment_our_todo_complete.xml
  presentation/src/main/res/layout/fragment_our_todo_uncomplete.xml
Labels: 상호 🍀, FIX 🔨

#163 [FIX/#162] 데이트 피커 오류 수정
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/choosedate/CreateTripActivity.kt
  presentation/src/main/res/values/strings.xml
Labels: 세연 🤤, FIX 🔨

#165 [CHORE/#164] version code 8 업데이트
  buildSrc/src/main/kotlin/Constants.kt
Labels: 상호 🍀, CHORE 🎀

#169 [CHORE/#168] version code 9 변경
  buildSrc/src/main/kotlin/Constants.kt
Labels: 상호 🍀, CHORE 🎀

#172 [FIX/#171] 스크롤 뷰 이슈 수정
  presentation/src/main/res/layout/activity_finish_trip.xml
Labels: 세연 🤤, FIX 🔨

#173 [FIX]/#170 2차 QA 반영
  app/src/main/AndroidManifest.xml
  buildSrc/src/main/kotlin/Constants.kt
  presentation/src/main/java/com/going/presentation/profile/ProfileActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/result/UserTendencyResultList.kt
  presentation/src/main/java/com/going/presentation/tendency/ttest/TendencyTestViewModel.kt
  presentation/src/main/java/com/going/presentation/util/ActivityExt.kt
  presentation/src/main/res/raw/doorip_splash.json
  presentation/src/main/res/values/strings.xml
Labels: 동민 🐥, FIX 🔨

#177 [CHORE/#174] README 최종 수정
  README.md
Labels: 상호 🍀, CHORE 🎀

#178 [HOTFIX/#176] EditText에서 HideKeyboard 수정
  buildSrc/src/main/kotlin/Constants.kt
  core-ui/src/main/java/com/going/ui/base/BaseActivity.kt
  presentation/src/main/res/layout/activity_private_detail.xml
  presentation/src/main/res/layout/activity_public_detail.xml
Labels: 상호 🍀, CHORE 🎀

#179 [HOTFIX/#175] 2차 QA 사항 수정
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/choosedate/BottomSheetDateContentFragment.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/choosedate/CreateTripViewModel.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/finish/InviteFinishActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/invitecode/EnterTripActivity.kt
  presentation/src/main/java/com/going/presentation/profile/ProfileActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultActivity.kt
  presentation/src/main/res/drawable/text_logo_doorip_red500.xml
  presentation/src/main/res/layout/activity_create_trip.xml
  presentation/src/main/res/layout/activity_enter_trip.xml
  presentation/src/main/res/layout/activity_my_todo_create.xml
  presentation/src/main/res/layout/activity_our_todo_create.xml
  presentation/src/main/res/values/strings.xml
Labels: 동민 🐥, HOTFIX 🚑️

#181 [CHORE/#180] 미사용 코드 삭제
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/going/doorip/di/DataSourceModule.kt
  app/src/main/java/com/going/doorip/di/RepositoryModule.kt
  app/src/main/java/com/going/doorip/di/ServiceModule.kt
  data/src/main/java/com/going/data/datasource/MockDataSource.kt
  data/src/main/java/com/going/data/datasourceImpl/MockDataSourceImpl.kt
  data/src/main/java/com/going/data/dto/response/MockFollowerResponseDto.kt
  data/src/main/java/com/going/data/repositoryImpl/MockRepositoryImpl.kt
  data/src/main/java/com/going/data/service/MockService.kt
  domain/src/main/kotlin/com/going/domain/entity/response/MockFollowerModel.kt
  domain/src/main/kotlin/com/going/domain/repository/MockRepository.kt
  presentation/src/main/java/com/going/presentation/mock/MockActivity.kt
  presentation/src/main/java/com/going/presentation/mock/MockAdapter.kt
  presentation/src/main/java/com/going/presentation/mock/MockViewHolder.kt
  presentation/src/main/java/com/going/presentation/mock/MockViewModel.kt
Labels: 동민 🐥, CHORE 🎀

#183 [CHORE/#182] version name 1.1 업데이트
  buildSrc/src/main/kotlin/Constants.kt
  presentation/src/main/java/com/going/presentation/setting/SettingActivity.kt
Labels: 상호 🍀, CHORE 🎀

#187 [REFACTOR/#184] custom view 구현 및 적용
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/going/presentation/designsystem/edittext/EditTextState.kt
  presentation/src/main/java/com/going/presentation/designsystem/edittext/EmojiCounterEditText.kt
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/OnboardingProfileSettingActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/SignUpActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/SignUpViewModel.kt
  presentation/src/main/res/layout/activity_onboarding_profile_setting.xml
  presentation/src/main/res/layout/activity_sign_up.xml
  presentation/src/main/res/layout/view_emoji_counter_edittext.xml
  presentation/src/main/res/values/attrs.xml
  presentation/src/main/res/values/strings.xml
Labels: 동민 🐥, REFACTOR ♻️

#186 [REFACTOR/#185] OurTodo, MyTodo 뷰 / 코드 리팩토링만
  presentation/src/main/java/com/going/presentation/todo/detail/TodoDetailNameAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/create/MyTodoCreateActivity.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/create/MyTodoCreateViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoListViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/name/TodoNameAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/name/TodoNameViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFriendAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/OurTodoCreateActivity.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/OurTodoCreateBottomSheet.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/OurTodoCreateViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/create/TodoCreateNameViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/invite/FriendInviteDialog.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoListViewHolder.kt
Labels: 상호 🍀, REFACTOR ♻️

#190 [REFACTOR/#188] 코드 리펙토링 및 navigate 확장함수 구현
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInViewModel.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/SignUpActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
  presentation/src/main/java/com/going/presentation/setting/SettingActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/splash/TendencySplashActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/ttest/TendencyTestActivity.kt
  presentation/src/main/java/com/going/presentation/util/ActivityExt.kt
  presentation/src/main/res/layout/activity_sign_in.xml
  presentation/src/main/res/layout/activity_tendency_result.xml
  presentation/src/main/res/layout/activity_tendency_splash.xml
  presentation/src/main/res/layout/fragment_our_todo_uncomplete.xml
Labels: 동민 🐥, ADD ➕, REFACTOR ♻️

#194 [REFACTOR/#191] chart CustomView 구현 및 적용
  presentation/src/main/java/com/going/presentation/designsystem/textview/ChartTextView.kt
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/SignUpActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/splash/TendencySplashActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/ttest/TendencyTestActivity.kt
  presentation/src/main/java/com/going/presentation/util/ActivityExt.kt
  presentation/src/main/res/layout/activity_tendency_result.xml
  presentation/src/main/res/layout/view_chart_textview.xml
  presentation/src/main/res/layout/view_emoji_counter_edittext.xml
  presentation/src/main/res/values/attrs.xml
Labels: 동민 🐥, REFACTOR ♻️
