Repository Team-Going/Going-Android, pull requests merged in 2024-02, with the labels that each got.

#196 [FIX/#195] image download 로직 변경 / 리프레시 토큰 만료시 페이지 이동 추가
  app/src/main/java/com/going/doorip/di/AuthInterceptor.kt
  app/src/main/java/com/going/doorip/di/RetrofitModule.kt
  data/build.gradle.kts
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultViewModel.kt
  presentation/src/main/java/com/going/presentation/tendency/ttest/TendencyTestActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/ttest/TendencyTestViewModel.kt
  presentation/src/main/java/com/going/presentation/util/ActivityExt.kt
Labels: 동민 🐥, FIX 🔨

#197 [REFACTOR/#192] 여행 대시 보드 뷰 / 코드 리팩토링
  presentation/src/main/java/com/going/presentation/dashboard/DashBoardActivity.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/completed/CompletedAdapter.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/completed/CompletedTripFragment.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/completed/CompletedViewHolder.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/ongoing/OngoingAdapter.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/ongoing/OngoingTripFragment.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/ongoing/OngoingViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/TodoActivity.kt
  presentation/src/main/res/layout/activity_check_friends.xml
  presentation/src/main/res/layout/activity_enter_preference.xml
  presentation/src/main/res/layout/activity_finish_preference.xml
Labels: 유빈 ❄, REFACTOR ♻️

#201 [REFACTOR/#199] clean code 적용 및 웹뷰 생성 확장함수 생성
  domain/src/main/kotlin/com/going/domain/entity/AuthState.kt
  domain/src/main/kotlin/com/going/domain/entity/SignInState.kt
  presentation/src/main/java/com/going/presentation/designsystem/edittext/EmojiCounterEditText.kt
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInViewModel.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/SignUpActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/SignUpViewModel.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/splash/SplashViewModel.kt
  presentation/src/main/java/com/going/presentation/setting/SettingActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/ttest/TendencyTestActivity.kt
  presentation/src/main/java/com/going/presentation/util/ActivityExt.kt
Labels: 동민 🐥, REFACTOR ♻️

#200 [REFACTOR/#193] 세연 담당 뷰 / 코드 리팩토링
  app/src/main/AndroidManifest.xml
  core-ui/src/main/java/com/going/ui/extension/IntExt.kt
  core-ui/src/main/java/com/going/ui/extension/IntentExt.kt
  presentation/src/main/java/com/going/presentation/dashboard/DashBoardActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/choosedate/CreateTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/choosedate/CreateTripViewModel.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/finish/FinishTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/preference/EnterPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/preference/ParcelableTripData.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/finish/InviteFinishActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/invitecode/EnterTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/preference/FinishPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/profile/ProfileActivity.kt
  presentation/src/main/java/com/going/presentation/profile/ProfileViewModel.kt
  presentation/src/main/res/layout/activity_profile.xml
Labels: 세연 🤤, REFACTOR ♻️

#214 [HOTFIX/#213] chart error 해결
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/view_chart_textview.xml
Labels: 동민 🐥, HOTFIX 🚑️

#202 [REFACTOR/#198] 유빈 담당 뷰 / 코드 리팩토링
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/finish/FinishTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/preference/EnterPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/preference/EnterPreferenceViewModel.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/preference/FinishPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/preferencetag/PreferenceTagAdapter.kt
  presentation/src/main/java/com/going/presentation/entertrip/preferencetag/PreferenceTagViewHolder.kt
  presentation/src/main/java/com/going/presentation/setting/SettingActivity.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/checkfriends/CheckFriendsActivity.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/checkfriends/CheckFriendsAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/checkfriends/CheckFriendsViewHolder.kt
  presentation/src/main/res/layout/layout_custom_snackbar.xml
Labels: 유빈 ❄, FIX 🔨, REFACTOR ♻️

#218 [ADD/#217] user 자리 없을때 두줄 처리
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/res/layout/activity_todo_detail.xml
  presentation/src/main/res/layout/item_my_todo.xml
  presentation/src/main/res/layout/item_our_todo.xml
  presentation/src/main/res/layout/item_todo_create_name.xml
  presentation/src/main/res/layout/item_todo_name.xml
  presentation/src/main/res/values/colors.xml
Labels: 동민 🐥, ADD ➕
