Repository Team-Going/Going-Android, pull requests merged in 2024-03, with the labels that each got.

#210 [FIX/#208] 투두 생성, 조회 뷰 / 메모 빈칸 대응 수정
  presentation/src/main/java/com/going/presentation/todo/create/TodoCreateActivity.kt
  presentation/src/main/java/com/going/presentation/todo/create/TodoCreateViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/detail/TodoDetailActivity.kt
  presentation/src/main/java/com/going/presentation/todo/detail/TodoDetailViewModel.kt
  presentation/src/main/res/drawable/ic_dropdown_gray700.xml
Labels: 상호 🍀, FIX 🔨

#221 [FEAT/#219] Todo / 할당 미지정된 투두 대응 & 2차 스프린트 요소 추가
  presentation/src/main/java/com/going/presentation/todo/create/TodoCreateViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoListViewHolder.kt
  presentation/src/main/res/drawable/ic_empty.xml
  presentation/src/main/res/drawable/ic_trip_info.xml
  presentation/src/main/res/drawable/img_trip_friends_banner.xml
  presentation/src/main/res/drawable/shape_rect_4_gray100_fill.xml
  presentation/src/main/res/layout/activity_todo_create.xml
  presentation/src/main/res/layout/fragment_our_todo.xml
  presentation/src/main/res/layout/item_my_todo.xml
  presentation/src/main/res/layout/item_our_todo.xml
  presentation/src/main/res/values/appearances.xml
  presentation/src/main/res/values/strings.xml
Labels: 상호 🍀, FEAT ✨

#215 [FEAT/#212] 여행 정보 수정 뷰 / UI 구현
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/choosedate/BottomSheetDateContentFragment.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/choosedate/CreateTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/choosedate/DateContentBottomSheet.kt
  presentation/src/main/java/com/going/presentation/todo/editinfo/EditDateBottomSheet.kt
  presentation/src/main/java/com/going/presentation/todo/editinfo/EditTripInfoActivity.kt
  presentation/src/main/java/com/going/presentation/todo/editinfo/EditTripInfoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/editinfo/TripQuitDialogFragment.kt
  presentation/src/main/res/layout/activity_create_trip.xml
  presentation/src/main/res/layout/activity_edit_trip_info.xml
  presentation/src/main/res/layout/fragment_edit_date_trip_bottom_sheet.xml
  presentation/src/main/res/layout/fragment_trip_quit_dialog.xml
  presentation/src/main/res/values/strings.xml
Labels: 세연 🤤, FEAT ✨, UI 💐

#224 [UI/#216] 취향 태그 뷰 / UI 구현
  presentation/src/main/java/com/going/presentation/todo/ourtodo/checkfriends/CheckFriendsActivity.kt
  presentation/src/main/res/drawable/layer_list_trip_friends_progress_bar.xml
  presentation/src/main/res/drawable/shape_rect_6_gray50_fill.xml
  presentation/src/main/res/layout/activity_check_friends.xml
  presentation/src/main/res/values/strings.xml
Labels: 유빈 ❄, FEAT ✨, UI 💐

#225 [UI/#223] trip profile 구현
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/going/presentation/profile/trip/TripProfileActivity.kt
  presentation/src/main/java/com/going/presentation/profile/trip/TripProfileCharacterFragment.kt
  presentation/src/main/java/com/going/presentation/profile/trip/TripProfileTagFragment.kt
  presentation/src/main/java/com/going/presentation/profile/trip/TripProfileViewPagerAdapter.kt
  presentation/src/main/res/drawable/img_trip_profile_empty.xml
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/activity_trip_profile.xml
  presentation/src/main/res/layout/fragment_trip_profile_character.xml
  presentation/src/main/res/layout/fragment_trip_profile_tag.xml
  presentation/src/main/res/values/strings.xml
Labels: 동민 🐥, UI 💐

#229 [FIX/#228] 디버그, 릴리즈 서버 분리
  app/build.gradle.kts
Labels: 상호 🍀, FEAT ✨

#235 [FEAT/#231] 여행 프로필 뷰 / 취향 태그 구현
  app/src/main/AndroidManifest.xml
  domain/src/main/kotlin/com/going/domain/entity/ProfilePreferenceData.kt
  presentation/src/main/java/com/going/presentation/profile/trip/TripProfileActivity.kt
  presentation/src/main/java/com/going/presentation/profile/trip/TripProfileTagFragment.kt
  presentation/src/main/java/com/going/presentation/profile/trip/TripProfileViewPagerAdapter.kt
  presentation/src/main/java/com/going/presentation/profile/trip/tripprofiletag/changetag/ChangeTagActivity.kt
  presentation/src/main/java/com/going/presentation/profile/trip/tripprofiletag/changetag/ChangeTagAdapter.kt
  presentation/src/main/java/com/going/presentation/profile/trip/tripprofiletag/changetag/ChangeTagViewHolder.kt
  presentation/src/main/java/com/going/presentation/profile/trip/tripprofiletag/changetag/ChangeTagViewModel.kt
  presentation/src/main/java/com/going/presentation/profile/trip/tripprofiletag/profiletag/PreferenceTagAdapter.kt
  presentation/src/main/java/com/going/presentation/profile/trip/tripprofiletag/profiletag/PreferenceTagViewHolder.kt
  presentation/src/main/java/com/going/presentation/profile/trip/tripprofiletag/profiletag/TripProfileTagDecoration.kt
  presentation/src/main/java/com/going/presentation/profile/trip/tripprofiletag/profiletag/TripProfileTagFragment.kt
  presentation/src/main/java/com/going/presentation/profile/trip/tripprofiletag/profiletag/TripProfileTagViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/checkfriends/CheckFriendsActivity.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/checkfriends/CheckFriendsAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/checkfriends/CheckFriendsViewHolder.kt
  presentation/src/main/res/layout/activity_change_tag.xml
  presentation/src/main/res/layout/fragment_trip_profile_tag.xml
  presentation/src/main/res/values/strings.xml
Labels: 유빈 ❄, FEAT ✨, UI 💐

#234 [FEAT/#233] 뷰 동적 크기 조정 및 버튼 연결, 제목 조정
  app/src/main/AndroidManifest.xml
  data/src/main/java/com/going/data/datasource/ProfileDataSource.kt
  data/src/main/java/com/going/data/datasourceImpl/ProfileDataSourceImpl.kt
  data/src/main/java/com/going/data/dto/request/ParticipantProfileRequestDto.kt
  data/src/main/java/com/going/data/dto/response/ParticipantProfileResponseDto.kt
  data/src/main/java/com/going/data/repositoryImpl/ProfileRepositoryImpl.kt
  data/src/main/java/com/going/data/service/ProfileService.kt
  domain/src/main/kotlin/com/going/domain/entity/request/ParticipantProfileRequestModel.kt
  domain/src/main/kotlin/com/going/domain/entity/response/ParticipantProfileResponseModel.kt
  domain/src/main/kotlin/com/going/domain/repository/ProfileRepository.kt
  presentation/src/main/java/com/going/presentation/profile/participant/ParticipantProfileActivity.kt
  presentation/src/main/java/com/going/presentation/profile/participant/ParticipantProfileCharacterFragment.kt
  presentation/src/main/java/com/going/presentation/profile/participant/ParticipantProfileTagFragment.kt
  presentation/src/main/java/com/going/presentation/profile/participant/ParticipantProfileViewModel.kt
  presentation/src/main/java/com/going/presentation/profile/participant/ParticipantProfileViewPagerAdapter.kt
  presentation/src/main/java/com/going/presentation/profile/trip/TripProfileActivity.kt
  presentation/src/main/java/com/going/presentation/profile/trip/TripProfileCharacterFragment.kt
  presentation/src/main/java/com/going/presentation/profile/trip/TripProfileViewPagerAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/checkfriends/CheckFriendsActivity.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/checkfriends/CheckFriendsViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/checkfriends/CheckFriendsViewModel.kt
  presentation/src/main/res/drawable/img_participate_profile_empty.png
  presentation/src/main/res/drawable/img_profile_guest.xml
  presentation/src/main/res/drawable/img_trip_profile_empty.xml
  presentation/src/main/res/layout/activity_participant_profile.xml
  presentation/src/main/res/layout/fragment_trip_profile_character.xml
  presentation/src/main/res/values/strings.xml
Labels: 동민 🐥, ADD ➕, FEAT ✨

#238 [FIX/#237] OurTodo / 엠프티뷰 수정 & 성향 미설정 아이템 대응
  presentation/src/main/java/com/going/presentation/todo/mytodo/MyTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/friendlist/OurTodoFriendViewHolder.kt
  presentation/src/main/res/layout/item_todo_friends.xml
Labels: 상호 🍀, FIX 🔨

#243 [FEAT/#236] 여행 프로필 뷰 / 취향 태그 수정 서버 통신 구현
  app/src/main/AndroidManifest.xml
  core-ui/src/main/java/com/going/ui/util/RVItemFirstLastDecoration.kt
  core-ui/src/main/java/com/going/ui/util/RvItemLastDecoration.kt
  data/src/main/java/com/going/data/datasource/ProfileDataSource.kt
  data/src/main/java/com/going/data/datasourceImpl/ProfileDataSourceImpl.kt
  data/src/main/java/com/going/data/dto/request/PreferenceChangeRequestDto.kt
  data/src/main/java/com/going/data/repositoryImpl/ProfileRepositoryImpl.kt
  data/src/main/java/com/going/data/service/ProfileService.kt
  domain/src/main/kotlin/com/going/domain/entity/request/PreferenceChangeRequestModel.kt
  domain/src/main/kotlin/com/going/domain/repository/ProfileRepository.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/DashBoardDecoration.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/completed/CompletedTripFragment.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/ongoing/OngoingTripFragment.kt
  presentation/src/main/java/com/going/presentation/entertrip/createtrip/preference/EnterPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/preference/FinishPreferenceActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/preferencetag/PreferenceTagDecoration.kt
  presentation/src/main/java/com/going/presentation/profile/participant/ParticipantProfileActivity.kt
  presentation/src/main/java/com/going/presentation/profile/participant/ParticipantProfileTagFragment.kt
  presentation/src/main/java/com/going/presentation/profile/participant/ParticipantProfileViewModel.kt
  presentation/src/main/java/com/going/presentation/profile/participant/ParticipantProfileViewPagerAdapter.kt
  presentation/src/main/java/com/going/presentation/profile/participant/profilecharacter/ParticipantProfileCharacterFragment.kt
  presentation/src/main/java/com/going/presentation/profile/participant/profiletag/ParticipantProfileTagAdapter.kt
  presentation/src/main/java/com/going/presentation/profile/participant/profiletag/ParticipantProfileTagFragment.kt
  presentation/src/main/java/com/going/presentation/profile/participant/profiletag/ParticipantProfileTagViewHolder.kt
  presentation/src/main/java/com/going/presentation/profile/participant/profiletag/changetag/ChangeTagActivity.kt
  presentation/src/main/java/com/going/presentation/profile/participant/profiletag/changetag/ChangeTagAdapter.kt
  presentation/src/main/java/com/going/presentation/profile/participant/profiletag/changetag/ChangeTagViewHolder.kt
  presentation/src/main/java/com/going/presentation/profile/participant/profiletag/changetag/ChangeTagViewModel.kt
  presentation/src/main/java/com/going/presentation/profile/trip/tripprofiletag/changetag/ChangeTagActivity.kt
  presentation/src/main/java/com/going/presentation/profile/trip/tripprofiletag/changetag/ChangeTagViewModel.kt
  presentation/src/main/java/com/going/presentation/profile/trip/tripprofiletag/profiletag/PreferenceTagViewHolder.kt
  presentation/src/main/java/com/going/presentation/profile/trip/tripprofiletag/profiletag/TripProfileTagFragment.kt
  presentation/src/main/java/com/going/presentation/profile/trip/tripprofiletag/profiletag/TripProfileTagViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoUncompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/checkfriends/CheckFriendsActivity.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoCompleteFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoUncompleteFragment.kt
  presentation/src/main/res/layout/fragment_participant_profile_character.xml
  presentation/src/main/res/layout/fragment_participant_profile_tag.xml
  presentation/src/main/res/layout/item_dash_board_completed.xml
  presentation/src/main/res/layout/item_dash_board_ongoing.xml
  presentation/src/main/res/layout/item_preference_tag.xml
  presentation/src/main/res/values/strings.xml
Labels: 유빈 ❄, FEAT ✨

#242 [FEAT/#240] tendency intent 분기처리
  presentation/src/main/java/com/going/presentation/onboarding/signin/SignInActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/SignUpActivity.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/SignUpViewModel.kt
  presentation/src/main/java/com/going/presentation/profile/my/ProfileActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultViewModel.kt
  presentation/src/main/java/com/going/presentation/tendency/splash/TendencySplashActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/splash/TendencySplashViewModel.kt
  presentation/src/main/java/com/going/presentation/tendency/ttest/TendencyTestActivity.kt
  presentation/src/main/java/com/going/presentation/tendency/ttest/TendencyTestViewModel.kt
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/activity_tendency_splash.xml
  presentation/src/main/res/values/strings.xml
Labels: 동민 🐥, FEAT ✨

#245 [FEAT/#244] 여행 친구 조회 뷰 / 서버 통신 구현
  data/src/main/java/com/going/data/dto/response/CheckFriendsResponseDto.kt
  domain/src/main/kotlin/com/going/domain/entity/response/CheckFriendsModel.kt
  presentation/src/main/java/com/going/presentation/entertrip/invitetrip/finish/InviteFinishActivity.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/checkfriends/CheckFriendsActivity.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/checkfriends/CheckFriendsViewModel.kt
  presentation/src/main/res/layout/activity_check_friends.xml
  presentation/src/main/res/values/strings.xml
Labels: 유빈 ❄, FEAT ✨

#247 [CHORE/#246] version code 1.2(12) 업데이트
  buildSrc/src/main/kotlin/Constants.kt
  presentation/src/main/java/com/going/presentation/setting/SettingActivity.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
Labels: 상호 🍀, CHORE 🎀

#254 [FIX/#253] Todo / 어댑터 네이밍 전체 수정
  presentation/src/main/java/com/going/presentation/todo/change/ChangeAllocatorAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/change/ChangeAllocatorViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/change/TodoChangeActivity.kt
  presentation/src/main/java/com/going/presentation/todo/create/CreateParticipantAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/create/CreateParticipantViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/create/TodoCreateActivity.kt
  presentation/src/main/java/com/going/presentation/todo/detail/DetailAllocatorAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/detail/DetailAllocatorViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/detail/TodoDetailActivity.kt
  presentation/src/main/java/com/going/presentation/todo/list/ListAllocatorAdapter.kt
  presentation/src/main/java/com/going/presentation/todo/list/ListAllocatorViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/mytodo/todolist/MyTodoListViewHolder.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/todolist/OurTodoListViewHolder.kt
Labels: 상호 🍀, FIX 🔨

#251 [FEAT/#249] 여행 친구 조회 뷰 / 엠티 뷰 구현
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/checkfriends/CheckFriendsActivity.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/checkfriends/CheckFriendsViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/invite/FriendInviteEmptyDialog.kt
  presentation/src/main/res/drawable/ic_empty_check_friends.xml
  presentation/src/main/res/layout/activity_check_friends.xml
  presentation/src/main/res/values/strings.xml
Labels: 유빈 ❄, FEAT ✨

#258 [FIX/#257] 유빈 담당 뷰 / QA 이슈 대응
  presentation/src/main/java/com/going/presentation/dashboard/DashBoardActivity.kt
  presentation/src/main/java/com/going/presentation/profile/participant/profiletag/changetag/ChangeTagActivity.kt
  presentation/src/main/java/com/going/presentation/profile/participant/profiletag/changetag/ChangeTagViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/checkfriends/CheckFriendsActivity.kt
  presentation/src/main/res/layout/activity_change_tag.xml
  presentation/src/main/res/layout/activity_check_friends.xml
  presentation/src/main/res/layout/activity_enter_preference.xml
  presentation/src/main/res/layout/activity_finish_preference.xml
Labels: 유빈 ❄, FIX 🔨

#260 [FIX/#252] QA사항 구현
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/going/presentation/designsystem/edittext/EmojiCounterEditText.kt
  presentation/src/main/java/com/going/presentation/onboarding/signup/SignUpActivity.kt
  presentation/src/main/java/com/going/presentation/profile/edit/ProfileEditViewModel.kt
  presentation/src/main/java/com/going/presentation/profile/my/ProfileActivity.kt
  presentation/src/main/java/com/going/presentation/profile/participant/ParticipantProfileActivity.kt
  presentation/src/main/java/com/going/presentation/profile/participant/profilecharacter/ParticipantProfileCharacterFragment.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/checkfriends/CheckFriendsViewHolder.kt
  presentation/src/main/res/layout/activity_participant_profile.xml
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/activity_profile_edit.xml
  presentation/src/main/res/layout/fragment_participant_profile_character.xml
  presentation/src/main/res/layout/view_emoji_counter_edittext.xml
  presentation/src/main/res/values/strings.xml
Labels: 동민 🐥, FIX 🔨

#259 [FIX/#256] 세연 담당 뷰 / QA 이슈 대응
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/going/presentation/todo/edittrip/info/EditTripInfoActivity.kt
  presentation/src/main/res/layout/activity_create_trip.xml
Labels: 세연 🤤, FIX 🔨

#261 [FIX/#255] Todo / QA 이슈사항 대응
  presentation/src/main/java/com/going/presentation/designsystem/edittext/EmojiCounterEditText.kt
  presentation/src/main/java/com/going/presentation/todo/detail/TodoDetailActivity.kt
  presentation/src/main/res/drawable/ic_empty.png
  presentation/src/main/res/drawable/ic_empty.xml
  presentation/src/main/res/drawable/ic_profile.xml
  presentation/src/main/res/drawable/img_ourtodo_main.xml
  presentation/src/main/res/layout/activity_todo_change.xml
  presentation/src/main/res/layout/activity_todo_create.xml
  presentation/src/main/res/layout/activity_todo_detail.xml
  presentation/src/main/res/layout/fragment_my_todo.xml
  presentation/src/main/res/layout/item_our_todo.xml
  presentation/src/main/res/layout/view_emoji_counter_edittext.xml
  presentation/src/main/res/values/attrs.xml
Labels: 상호 🍀, FIX 🔨

#266 [FIX/#265] Todo / 2차 QA 이슈 대응
  presentation/src/main/java/com/going/presentation/todo/detail/TodoDetailActivity.kt
  presentation/src/main/java/com/going/presentation/todo/detail/TodoDetailViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/edittrip/edit/EditTripActivity.kt
  presentation/src/main/java/com/going/presentation/todo/edittrip/edit/EditTripViewModel.kt
  presentation/src/main/res/layout/activity_edit_trip.xml
  presentation/src/main/res/layout/activity_todo_detail.xml
  presentation/src/main/res/layout/fragment_my_todo.xml
  presentation/src/main/res/values/strings.xml
Labels: 상호 🍀, FIX 🔨

#268 [FIX/#263] 유빈 담당 뷰 / 2차 QA 이슈 대응
  presentation/src/main/java/com/going/presentation/profile/participant/ParticipantProfileViewModel.kt
  presentation/src/main/java/com/going/presentation/profile/participant/profiletag/changetag/ChangeTagViewModel.kt
  presentation/src/main/res/drawable/ic_empty_check_friends.xml
  presentation/src/main/res/layout/activity_check_friends.xml
Labels: 유빈 ❄, FIX 🔨

#269 [FIX/#267] 세연 담당 뷰 / 2차 QA 이슈 대응
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/going/presentation/entertrip/edittrip/QuitTripDialogFragment.kt
  presentation/src/main/java/com/going/presentation/entertrip/edittrip/detail/DetailTripActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/edittrip/detail/DetailTripViewModel.kt
  presentation/src/main/java/com/going/presentation/entertrip/edittrip/editinfo/EditDateBottomSheet.kt
  presentation/src/main/java/com/going/presentation/entertrip/edittrip/editinfo/EditTripInfoActivity.kt
  presentation/src/main/java/com/going/presentation/entertrip/edittrip/editinfo/EditTripInfoViewModel.kt
  presentation/src/main/java/com/going/presentation/todo/ourtodo/OurTodoFragment.kt
  presentation/src/main/res/layout/activity_detail_trip.xml
  presentation/src/main/res/layout/activity_edit_trip_info.xml
Labels: 세연 🤤, FIX 🔨

#271 [FIX/#270] 여행 수정 뷰 / 백버튼 수정
  presentation/src/main/java/com/going/presentation/dashboard/triplist/completed/CompletedTripFragment.kt
  presentation/src/main/java/com/going/presentation/dashboard/triplist/ongoing/OngoingTripFragment.kt
Labels: 세연 🤤, FIX 🔨

#277 [FIX/#276] 3차 qa: intent 전달
  presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultActivity.kt
Labels: 동민 🐥, FIX 🔨

#273 [FIX/#272] 유빈 담당 뷰 / 3차 QA 이슈 대응
  presentation/src/main/res/layout/activity_check_friends.xml
Labels: 유빈 ❄, FIX 🔨

#275 [FIX/#274] 세연 담당 뷰 / 3차 QA 이슈 대응
  presentation/src/main/res/values/strings.xml
Labels: 세연 🤤, FIX 🔨
